### ISSUE TITLE
[ExtendedSplashScreen][Android] Content does not match native splash screen

### ISSUE THREAD

**Issue by kazo0** [unoplatform/uno.toolkit.ui#1054]
> I'm trying to use the Uno Toolkit's ExtendedSplashScreen control to create an extended splash screen for our app using this
[documentation](https://platform.uno/docs/articles/external/uno.toolkit.ui/doc/controls/ExtendedSplashScreen.html). While I'm now able to display an extended splash screen, it's slightly different from the native splashscreen, causing a jarring transition. I was wondering if you had any guidance for how to make sure the extended splashscreen can match exactly the native splash screen (plus a loading wheel of some kind). This functionality is why we previously used nventive's
[ExtendedSplashScreen library](https://github.com/nventive/ExtendedSplashScreen).
_- @juliecantin on Teams_

> The video was taken on an emulator running android 11. The sample was created by the Uno wizard, so I imagine it targets the latest version of the SDK. The app I'm having issues with, targets Uno 4 and Android SDK 13

[extendedsplash.webm](https://github.com/unoplatform/uno.toolkit.ui/assets/4793020/1cd2f3ac-4935-4436-aa57-40ca26f892fb)

> I also tested the extended splash screen on my physical pixel 6 Android 13 device, and here the extended splash screen doesn't seem to automatically include the native splash screen at all. Recording here (from the same sample app, no change except to make the background of the main page white)

https://github.com/unoplatform/uno.toolkit.ui/assets/4793020/15ad93f6-4f0b-4b24-bd0f-e0e080a5fb4a

Repro app:
[extendedsplash.zip](https://github.com/unoplatform/uno.toolkit.ui/files/14435730/extendedsplash.zip)

**Comment by Marc-Antoine-Soucy** [comment]
For android 13-14, it says in [the documentation](https://platform.uno/docs/articles/external/uno.toolkit.ui/doc/controls/ExtendedSplashScreen.html) that it wont show the native splashscreen image

**Comment by juliecantin** [comment]
I hadn't understood that. This makes the control not particularly useful for my app. The bug still exists for Android 11-, though.

**Comment by kazo0** [comment]
> For android 13-14, it says in [the documentation](https://platform.uno/docs/articles/external/uno.toolkit.ui/doc/controls/ExtendedSplashScreen.html) that it wont show the native splashscreen image. ![image](https://private-user-images.githubusercontent.com/90481654/308698195-8bc7b15a-c9fb-41ac-bac6-3ed8ef5807ff.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkxNjQ3NzQsIm5iZiI6MTcwOTE2NDQ3NCwicGF0aCI6Ii85MDQ4MTY1NC8zMDg2OTgxOTUtOGJjN2IxNWEtYzlmYi00MWFjLWJhYzYtM2VkOGVmNTgwN2ZmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI4VDIzNTQzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNjMDFlODlhNGQ1MTk0YmQyZWE4Yzg5YTEyMDc5NjA4ZGU0NDAzOWIxOTc2ZmYxZGExZTkyMjE1MWIzMzRhNGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.P-qbvou7hHCLxHANr_jGCNLVqAJhPab0Q5l-WMLeQrU)

@nickrandolph are we understanding that correctly? We shouln't be seeing a blank screen on android 12+ though, no?
