### ISSUE TITLE
error CS1503: Argument 1: cannot convert from 'Microsoft.UI.Xaml.Controls.NavigationView' to 'Uno.Toolkit.UI.DrawerControl'

### ISSUE THREAD

**Issue by IneedHelp** [unoplatform/uno.toolkit.ui#1055]
## On which page?
https://platform.uno/docs/articles/external/uno.toolkit.ui/doc/controls/DrawerControl.html#navigationview-with-drawer
## What's wrong?
error CS1503: Argument 1: cannot convert from 'Microsoft.UI.Xaml.Controls.NavigationView' to 'Uno.Toolkit.UI.DrawerControl' when trying to compile that code
## Any feedback?
removing `utu:DrawerControlBehavior.FitToDrawerContent="False"` makes the code compile fine

**Comment by kazo0** [comment]
Hi @IneedHelp, thanks for the report!

Interesting, I will take a quick look with a sample app to see what the issue is. 

And in your code you are setting Style the of the `NavigationBar` to `DrawerNavigationViewStyle` and you have properly initialized the ToolkitResources from the [Getting Started](https://platform.uno/docs/articles/external/uno.toolkit.ui/doc/getting-started.html)?

I will test on my side and see if maybe we need to make some updates on this page, thanks!

**Comment by IneedHelp** [comment]
Hello @kazo0 ,
I just used the sample code as it is in a fresh solution
`<muxc:NavigationView PaneTitle="Gesture NavView"
                     OpenPaneLength="320"
                     utu:DrawerControlBehavior.FitToDrawerContent="False"
                     Style="{StaticResource DrawerNavigationViewStyle}">
    <muxc:NavigationView.MenuItems>
        <muxc:NavigationViewItem Content="Home"/>
        <muxc:NavigationViewItem Content="Page 1"/>
        <muxc:NavigationViewItem Content="Page 2"/>
        <muxc:NavigationViewItem Content="Page 3"/>
    </muxc:NavigationView.MenuItems>
    <muxc:NavigationView.Content>
        <Frame x:Name="contentFrame"/>
    </muxc:NavigationView.Content>
</muxc:NavigationView>`
the style `Style="{StaticResource DrawerNavigationViewStyle}"` does influence the look, but whether it exists or not does not influence the compilation process.
Compilation fails because of `utu:DrawerControlBehavior.FitToDrawerContent`

and yes, I do have
`
<ToolkitResources xmlns="using:Uno.Toolkit.UI" />` in the merged dictionaries.

**Comment by kazo0** [comment]
Thanks @IneedHelp, nice catch! We will get this fixed as it is definitely an issue

**Comment by IneedHelp** [comment]
> Thanks @IneedHelp, nice catch! We will get this fixed as it is definitely an issue

@kazo0 Thank you for the prompt responses.
