### ISSUE TITLE
NavigationBar is not working using C# Markup

### ISSUE THREAD

**Issue by abbatepabloo** [unoplatform/uno.toolkit.ui#1066]
## Current behavior
When you use Fluent theme, the NavigationBar is not visible unless you resize the windows. If you use Material theme the NavigationBar is visible without resizing.

When the navigation bar is visible and you click on the back arrow nothing happens (Tested on Fluent and Material themes)

## Expected behavior
The NavigationBar should always be visible and when you click the back arrow it should navigate backward. Exactly as it happens if you use Xaml instead of C# Markup.

## How to reproduce it (as minimally and precisely as possible)
Using Visual Studio and the UNO templates (5.1.22) create a new project for **Uno Platform App** and customize the **Recommended** options:
* Platform: **GTK**
* Presentation: **MVVM**
* Markup: **C# Markup**

Leave all the other settings as default.

Run the app (*.Gtk) and when the Main window is presented click the button **Go to the Second Page**. Once you get there, you won't be able to see the navigation bar if you selected Fluent theme, you need to resize the window. If you selected Material Theme the NavigationBar will be visible without resizing the window.

When the NavigationBar is visible click on the back arrow. Nothing will happen, it should return to the MainPage.

Nuget Package:

Package Version(s):
```
    <PackageVersion Include="CommunityToolkit.Mvvm" Version="8.2.2" />
    <PackageVersion Include="Microsoft.Extensions.Logging.Console" Version="8.0.0" />
    <PackageVersion Include="coverlet.collector" Version="6.0.0" />
    <PackageVersion Include="FluentAssertions" Version="6.12.0" />
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="17.8.0" />
    <PackageVersion Include="NUnit" Version="4.0.1" />
    <PackageVersion Include="NUnit3TestAdapter" Version="4.5.0" />
    <PackageVersion Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageVersion Include="SkiaSharp.Skottie" Version="2.88.7" />
    <PackageVersion Include="SkiaSharp.Views.Uno.WinUI" Version="2.88.7" />
    <PackageVersion Include="Swashbuckle.AspNetCore" Version="6.5.0" />
    <PackageVersion Include="Uno.Core.Extensions.Logging.Singleton" Version="4.0.1" />
    <PackageVersion Include="Uno.Extensions.Core.WinUI" Version="4.0.0" />
    <PackageVersion Include="Uno.Extensions.Configuration" Version="4.0.0" />
    <PackageVersion Include="Uno.Extensions.Hosting" Version="4.0.0" />
    <PackageVersion Include="Uno.Extensions.Hosting.WinUI" Version="4.0.0" />
    <PackageVersion Include="Uno.Extensions.Http" Version="4.0.0" />
    <PackageVersion Include="Uno.Extensions.Http.WinUI" Version="4.0.0" />
    <PackageVersion Include="Uno.Extensions.Http.Refit" Version="4.0.0" />
    <PackageVersion Include="Uno.Extensions.Localization" Version="4.0.0" />
    <PackageVersion Include="Uno.Extensions.Localization.WinUI" Version="4.0.0" />
    <PackageVersion Include="Uno.Extensions.Logging.WinUI" Version="4.0.0" />
    <PackageVersion Include="Uno.Extensions.Navigation" Version="4.0.0" />
    <PackageVersion Include="Uno.Extensions.Navigation.WinUI" Version="4.0.0" />
    <PackageVersion Include="Uno.Extensions.Navigation.Toolkit.WinUI" Version="4.0.0" />
    <PackageVersion Include="Uno.Extensions.Serialization" Version="4.0.0" />
    <PackageVersion Include="Uno.Extensions.Serialization.Http" Version="4.0.0" />
    <PackageVersion Include="Uno.Extensions.Serialization.Refit" Version="4.0.0" />
    <PackageVersion Include="Uno.Toolkit.WinUI" Version="5.1.7" />
    <PackageVersion Include="Uno.Resizetizer" Version="1.3.0" />
    <PackageVersion Include="Uno.UI.Adapter.Microsoft.Extensions.Logging" Version="$(UnoVersion)" />
    <PackageVersion Include="Uno.UniversalImageLoader" Version="1.9.36" />
    <PackageVersion Include="Uno.WinUI" Version="$(UnoVersion)" />
    <PackageVersion Include="Uno.WinUI.Lottie" Version="$(UnoVersion)" />
    <PackageVersion Include="Uno.WinUI.Markup" Version="5.1.5" />
    <PackageVersion Include="Uno.Extensions.Markup.Generators" Version="5.1.5" />
    <PackageVersion Include="Uno.Toolkit.WinUI.Markup" Version="5.1.3" />
    <PackageVersion Include="Uno.Extensions.Navigation.WinUI.Markup" Version="4.0.0" />
    <PackageVersion Include="Uno.Themes.WinUI.Markup" Version="4.1.1" />
    <PackageVersion Include="Uno.WinUI.DevServer" Version="$(UnoVersion)" />
    <PackageVersion Include="Uno.WinUI.Skia.Gtk" Version="$(UnoVersion)" />
    <PackageVersion Include="Uno.UITest.Helpers" Version="1.1.0-dev.70" />
    <PackageVersion Include="Xamarin.UITest" Version="4.3.3" />
```
Affected platform(s):

- [ ] WebAssembly
- [ ] Android
- [ ] iOS
- [ ] macOS (AppKit)
- [ ] Mac Catalyst
- [ ] Skia
  - [ ] WPF
  - [X] GTK (Linux)
  - [ ] Linux Framebuffer
  - [ ] Tizen
- [ ] Windows

IDE:

- [X] Visual Studio 2022
- [ ] Visual Studio 2019
- [ ] Visual Studio Code
- [ ] Visual Studio for Mac
- [ ] Rider Windows
- [ ] Rider macOS

Relevant plugins:

**Comment by agneszitte** [comment]
@abbatepabloo are you able to provide us with a sample app where you can reproduce the issue, please?

**Comment by kazo0** [comment]
@abbatepabloo / @agneszitte / @vatsashah45 

Following the steps in the original post, I am able to repro with the following sample:

[UnoApp13.zip](https://github.com/unoplatform/uno.toolkit.ui/files/14602811/UnoApp13.zip)

**Comment by kazo0** [comment]
Can confirm this is an issue for all Uno-based platforms
