### ISSUE TITLE
[TopTabBar - Material] SelectionIndicator appears wider than TabBarItem in certain layouts

### ISSUE THREAD

**Issue by kazo0** [unoplatform/uno.toolkit.ui#109]
## Current behavior

![MicrosoftTeams-image](https://user-images.githubusercontent.com/4793020/141792557-50f71fea-624e-4734-8855-a63d27108ea3.png)

## Expected behavior

SelectionIndicator should only be as wide as the TabBarItem

## Environment

Nuget Package:

Package Version(s):

Affected platform(s):

- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renders for Xamarin.Forms
- [ ] Windows
- [ ] Build tasks

Visual Studio:

- [ ] 2017 (version: )
- [ ] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by Xiaoy312** [comment]
idk if this would be helpful, Ripple likes to bloat to 2-3x the size of content it holds
to confirm this, you can play with the [Ripple::RippleSizeMultiplier](https://github.com/unoplatform/Uno.Themes/blob/master/src/library/Uno.Material/Controls/Ripple.cs#L160-L161) and see if the indicator scales accordingly
