### ISSUE TITLE
Recommended template progress ring is always running

### ISSUE THREAD

**Issue by jeromelaban** [unoplatform/uno.toolkit.ui#1099]
### Current behavior

The progress ring animation is not stopped even after the splashscreen is removed

### Expected behavior

ProgressRing is stopped

### Affected platforms

Skia

### Template Host

dotnet new

### Host OS

Windows

### Template Options

Recommeded

### Template Version

```shell
5.2
```

**Comment by kazo0** [comment]
@nickrandolph this can be closed now, right?
