### ISSUE TITLE
TabBar nests TabBarItems when being set as ItemTemplate's root

### ISSUE THREAD

**Issue by kazo0** [unoplatform/uno.toolkit.ui#1129]
With the following XAML

```xml
<utu:TabBar SelectedIndex="3"
			ItemsSource="{Binding Data.Items}"
			Style="{StaticResource TopTabBarStyle}">
	<utu:TabBar.ItemTemplate>
		<DataTemplate>
			<utu:TabBarItem Background="Red" Content="Content" />
		</DataTemplate>
	</utu:TabBar.ItemTemplate>
</utu:TabBar>
```

We should be seeing this:

<img alt="image" src="https://github.com/unoplatform/uno.toolkit.ui/assets/4793020/e6d993ff-87c6-486f-b307-b6d4a56ed9f7">

Instead, we are seeing that that TabBar now contains TabBarItems that contain the red TabBarItem as it's content:

<img alt="image" src="https://github.com/unoplatform/uno.toolkit.ui/assets/4793020/cdc00025-cf47-4a2b-884e-cceac8d57be8">

**Comment by Xiaoy312** [comment]
ChipGroup\Chip suffers the same problem

Both ChipGroup and TabBar inherits from ItemsControl, and both override GetContainerForItemOverride+IsItemItsOwnContainerOverride.
This handles the case where the Items or ItemsSource contains the proper type for its item "container". However, it does not support the case where the supposed "container" is coming from the result of ItemTemplate.

That said, ListView and ListViewItem works... both on Windows and Uno somehow...
On Uno, this is done via [ItemsControl::GetRootOfItemTemplateAsContainer implemented in Selector](https://github.com/unoplatform/uno/blob/5.0.0/src/Uno.UI/UI/Xaml/Controls/Primitives/Selector.cs#L667).
It is unclear how Windows is handling this..?

**Comment by iurycarlos** [comment]
Something similar in https://github.com/unoplatform/uno.toolkit.ui/issues/1256

**Comment by kazo0** [comment]
@iurycarlos is this blocking for your work on the project? We may want to prioritize this one

**Comment by iurycarlos** [comment]
It is blocking just a datail in UI.
I don't think it is crucial for first version, but would be nice to have it in the finished UI.

**Comment by jhanvi03** [comment]
@Darsh0307 Could you please verify?
