### ISSUE TITLE
Layout cycle detected when resizing a view that has a NavigationView and TabBar

### ISSUE THREAD

**Issue by ArchieCoder** [unoplatform/uno.toolkit.ui#1131]
### Current behavior

When the view gets smaller, an exception is fired and the app crashes

### Expected behavior

No crash

### How to reproduce it (as minimally and precisely as possible)

[UnoTabApp.zip](https://github.com/unoplatform/uno/files/15276383/UnoTabApp.zip)

or

1- Create a new project with the default option (Fluent and Materal, it's irrevelant).
2- Copy paste the page content of the HomePage from Commerce app. The goal is to test the NavigationView + Tab bar. Fix the namespaces.
3- Deploy and resize the app.

### Works on UWP/WinUI

None

### NuGet package version(s)

5.2.121

### Affected platforms

Windows (WinAppSDK)

**Comment by carldebilly** [comment]
Cause of the bug has been found and this PR should fix it: https://github.com/unoplatform/uno.toolkit.ui/pull/1138

Thanks @ArchieCoder for reporting this bug!

cc @kazo0
