### ISSUE TITLE
[Shadow Container] Allow clicking on elements under the shadow

### ISSUE THREAD

**Issue by rafael-rosa-knowcode** [unoplatform/uno.toolkit.ui#1139]
## What would you like to be added:

I would like that when using a ShadowContainer, the area informed to have the Shadow allowed clicking.
Because for some cases we can put the shadow to one side and allow clicking on the other.

As it stands today, if I determine 200 pixels of OffsetY/OffsetX/Spread the element does not allow clicking in the areas in which it is reserving but it is not showing anything.
However, in the areas where it is reserving but is showing the click, it is possible to click.

For example, the image below shows where clicking is and is not allowed.

Assume that each square is 300px and that the shadow is 200.
And in the blue area the click is not allowed.

![image](https://github.com/unoplatform/uno.toolkit.ui/assets/116665025/661a775b-2649-4789-bf80-c42fdf3047c2)

And the Video of the demo.

https://github.com/unoplatform/uno.toolkit.ui/assets/116665025/3230ccfb-8684-496a-bdb0-86d5d9a46414

Code

```xaml

      <Grid ColumnDefinitions="300,300,300" RowDefinitions="300,300,300">
        <TextBox Grid.Row="0" Grid.Column="0" PlaceholderText="Grid 0 0" />
        <TextBox Grid.Row="0" Grid.Column="1" PlaceholderText="Grid 0 1" />
        <TextBox Grid.Row="0" Grid.Column="2" PlaceholderText="Grid 0 2" />
        <TextBox Grid.Row="1" Grid.Column="0" PlaceholderText="Grid 1 0" />
        <TextBox  PlaceholderText="Grid 1 1" />

        <ContentControl Grid.Row="1" Grid.Column="1" Style="{StaticResource CardSurfaceStyle}">
            <TextBox PlaceholderText="Grid 1 1" />
        </ContentControl>

        <TextBox Grid.Row="1" Grid.Column="2" PlaceholderText="Grid 1 2" />
        <TextBox Grid.Row="2" Grid.Column="0" PlaceholderText="Grid 2 0" />
        <TextBox Grid.Row="2" Grid.Column="1" PlaceholderText="Grid 2 1" />
        <TextBox Grid.Row="2" Grid.Column="2" PlaceholderText="Grid 2 2" />
      </Grid>
```

There is a Repro project attached to this issue.

[ShadowsIssue.zip](https://github.com/unoplatform/uno.toolkit.ui/files/15336643/ShadowsIssue.zip)

## Why is this needed:

To allow the user uses the ShadowsContainer and other elements.

## For which Platform:

- [x] WebAssembly
- [ ] Android
- [ ] iOS
- [ ] macOS (AppKit)
- [ ] Mac Catalyst
- [x] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Linux Framebuffer
  - [ ] Tizen
- [ ] Windows

**Comment by agneszitte** [comment]
@rafael-rosa-knowcode is this a blocker for any project at the moment?
fyi @kazo0
