### ISSUE TITLE
[ExtendedSplashScreen] Splashscreen Image Not Visible

### ISSUE THREAD

**Issue by agneszitte** [unoplatform/uno.toolkit.ui#1185]
### Current behavior

The splashscreen image is not visible for the ExtendedSplashScreen. 

**WASM for example:**
```
fail: Uno.Toolkit.UI.ExtendedSplashScreen[0]
      Error while getting native splash screen.
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Uno.Toolkit.UI.ExtendedSplashScreen.<>c.<LoadSplashScreenFromWasmManifest>b__33_2(String[] x) in D:\a\1\s\src\Uno.Toolkit.UI\Controls\ExtendedSplashScreen\ExtendedSplashScreen.Windows.crossruntime.cs:line 101
   at Uno.Toolkit.UI.EnumerableExtensions.ToDictionarySafe[String[],String,String](IEnumerable`1 source, Func`2 keySelector, Func`2 valueSelector) in D:\a\1\s\src\Uno.Toolkit.UI\Extensions\EnumerableExtensions.cs:line 90
   at Uno.Toolkit.UI.ExtendedSplashScreen.LoadSplashScreenFromWasmManifest() in D:\a\1\s\src\Uno.Toolkit.UI\Controls\ExtendedSplashScreen\ExtendedSplashScreen.Windows.crossruntime.cs:line 99
```
![image](https://github.com/user-attachments/assets/78d343ec-1b71-4869-b0af-5e657d1431b9)

### Expected behavior

The splashscreen image should be visible on all platforms for the ExtendedSplashScreen.

### How to reproduce it (as minimally and precisely as possible)

1. Create a new project with Toolkit as an option.
2. Launch the application on various platforms.
3. Observe the ExtendedSplashScreen and notice that the splashcreen image is not visible.

Sample app used for the tests and created with cli: [RecommendedAppTest.zip](https://github.com/user-attachments/files/16186530/RecommendedAppTest.zip)

### Workaround

N/A

### Affected Platforms

- [X] All (Each platform will need to undergo re-testing during the investigation)

### Version(s)

- Uno.Templates: 5.3.24
- Uno.Sdk: 5.3.24

### IDE

Microsoft Visual Studio Professional 2022 (64-bit) - Current Version 17.10.4

### Relevant plugins

N/A

### Anything else we need to know?

I am not getting the exception @nickrandolph mentioned on this issue https://github.com/unoplatform/uno.toolkit.ui/issues/1165 for WinAppSDK Unpackaged with the latest versions.

**Comment by agneszitte** [comment]
fyi @jeromelaban, @kazo0

**Comment by Xiaoy312** [comment]
cant seem to load the project:

> D:\code\uno\tests\RecommendedAppTest\RecommendedAppTest\RecommendedAppTest.csproj : error  : The SDK 'Uno.Sdk' specified could not be found.  D:\code\uno\tests\RecommendedAppTest\RecommendedAppTest\RecommendedAppTest.csproj

**Comment by agneszitte** [comment]
> cant seem to load the project:
> 
> > D:\code\uno\tests\RecommendedAppTest\RecommendedAppTest\RecommendedAppTest.csproj : error  : The SDK 'Uno.Sdk' specified could not be found.  D:\code\uno\tests\RecommendedAppTest\RecommendedAppTest\RecommendedAppTest.csproj

you will need the dev feed @Xiaoy312
