### ISSUE TITLE
[Android] Element with utu:Responsive doesn't display

### ISSUE THREAD

**Issue by rajamatt** [unoplatform/uno.toolkit.ui#1198]
## Current behavior

When navigating to a page with utu:Responsive, Android fails to load the page elements. The console doesn't seem to show anything.

![AndroidWithResponsive](https://github.com/user-attachments/assets/5cf0c889-c471-4719-8001-94a35cfe15e3)

## Expected behavior

By removing all `utu:Responsive`, the page elements appear:

![AndroidWithoutResponsive](https://github.com/user-attachments/assets/7efc5088-6cce-40e0-ab1d-fc646cbf26ce)

## How to reproduce it (as minimally and precisely as possible)

1) Add utu:Responsive to an element.
2) Try to navigate to that page with Android platform.
3) Notice that the page doesn't display all controls.

[ResponsiveAndroid.zip](https://github.com/user-attachments/files/16283571/ResponsiveAndroid.zip)

Nuget Package:

Toolkit: 6.2-dev.12

Package Version(s):

Affected platform(s):

- [ ] WebAssembly
- [x] Android
- [ ] iOS
- [ ] macOS (AppKit)
- [ ] Mac Catalyst
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Linux Framebuffer
  - [ ] Tizen
- [ ] Windows

IDE:

- [x] Visual Studio 2022
- [ ] Visual Studio 2019
- [ ] Visual Studio Code
- [ ] Visual Studio for Mac
- [ ] Rider Windows
- [ ] Rider macOS

Relevant plugins:

**Comment by Xiaoy312** [comment]
```
System.Reflection.AmbiguousMatchException: 'Ambiguous match found for 'Microsoft.UI.Xaml.UIElement Microsoft.UI.Xaml.Visibility Visibility'.'
    00 ResponsiveAndroid.Presentation.MainPage..ctor at D:\code\uno\tests\tlk1198\ResponsiveAndroid\Presentation\MainPage.xaml.cs:7,9
    01 ResponsiveAndroid.Presentation.MainPage.InitializeComponent at D:\code\uno\tests\tlk1198\ResponsiveAndroid\Uno.UI.SourceGenerators\Uno.UI.SourceGenerators.XamlGenerator.XamlCodeGenerator\MainPage_59923fc8d628b332ceb247423bc489a4.cs:72,4
    02 Uno.UI.Helpers.Xaml.ApplyExtensions.GenericApply<Microsoft.UI.Xaml.Controls.StackPanel, ResponsiveAndroid.Presentation.MainPage, Microsoft.UI.Xaml.NameScope> at C:\a\1\s\src\Uno.UI\UI\Xaml\Markup\ApplyExtensions.cs:58,4
    03 ResponsiveAndroid.Presentation.MainPage.<>c.<InitializeComponent>b__7_4 at D:\code\uno\tests\tlk1198\ResponsiveAndroid\Uno.UI.SourceGenerators\Uno.UI.SourceGenerators.XamlGenerator.XamlCodeGenerator\MainPage_59923fc8d628b332ceb247423bc489a4.cs:147,7
    04 Microsoft.UI.Xaml.Markup.MarkupExtension.Microsoft.UI.Xaml.Markup.IMarkupExtensionOverrides.ProvideValue at C:\a\1\s\src\Uno.UI\UI\Xaml\Markup\MarkupExtensions.cs:13,90
    05 Uno.Toolkit.UI.ResponsiveExtension.ProvideValue at D:\a\1\s\src\Uno.Toolkit.UI\Markup\ResponsiveExtension.cs:88,3
    06 Uno.Toolkit.UI.DependencyObjectExtensions.FindDependencyPropertyInfo at D:\a\1\s\src\Uno.Toolkit.UI\Extensions\DependencyObjectExtensions.cs:219,5
    07 Uno.Toolkit.UI.DependencyObjectExtensions.<FindDependencyPropertyInfo>g__GetDetails|13_0 at D:\a\1\s\src\Uno.Toolkit.UI\Extensions\DependencyObjectExtensions.cs:234,7
    08 System.Type.GetProperty at /_/src/libraries/System.Private.CoreLib/src/System/Type.cs:378,79
    09 System.RuntimeType.GetPropertyImpl at /_/src/mono/System.Private.CoreLib/src/System/RuntimeType.Mono.cs:866,86
```
