### ISSUE TITLE
Command not executed for `ListView.ItemClicked` when `ItemsSource` bound to `FeedView`

### ISSUE THREAD

**Issue by ProphetLamb** [unoplatform/uno.toolkit.ui#1229]
## Current behavior

The bound command is not executed.

## Expected behavior

The bound command is executed.

## How to reproduce it (as minimally and precisely as possible)

This minimum working sample uses the new template. Create a UNO project wit C# markup.

Add a list, a method to filter the list and a command to execute on click to the model.
```csharp
public IListState<string> Fruit => ListState<string>.Value(this, () => ["Apple", "Bannana", "Citrus"]);

public IListFeed<string> FilteredFruit => Feed.Combine(Name, Fruit.AsFeed()).Select(t => t.Item2.Where(f => f.Contains(t.Item1)).ToImmutableList()).AsListFeed();

public async Task FruitClicked(object selecteditem)
{
    await Name.UpdateAsync(n => selecteditem.ToString());
}
```

First, confirm that the items click action is executed on the `Fruit` list.

```csharp
new ListView()
    .Grid(row: 2)
    .ItemsSource(() => vm.Fruit)
    .IsItemClickEnabled(true)
    .CommandExtensions(b => b.Command(() => vm.FruitClicked))
```

Click `Apple` and the `TextBox` text is set to `Apple`. Great it works!

Now we wrap the `ListView` in a `FeedView` and bind the `Source` to `FilteredFruit`.

```csharp
new FeedView()
    .Grid(row: 2)
    .Source(() => vm.FilteredFruit)
    .ValueTemplate(() =>
        new ListView()
            .ItemsSource(x => x.Binding("Data"))
            .IsItemClickEnabled(true)
            .CommandExtensions(b => b.Command(() => vm.FruitClicked))
    )
```

Side note: Please do let me know how to bind the data source using a typed binding instead of the XPath `Data`.

Launch the app and test the filter.

![image](https://github.com/user-attachments/assets/c3c7173d-b383-4582-ab8c-47c081afabc7)

Great! It works.

Now click `Apple`. I expect the `TextBox` to show `Apple`, just like before.
Nothing happens. No error. Nothing.

How do I make this work? Any advice is much appreciated. Thanks in advance!

Nuget Package:

Package Version(s):

Affected platform(s):

- [x] WebAssembly
- [?] Android
- [?] iOS
- [?] macOS (AppKit)
- [?] Mac Catalyst
- [x] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Linux Framebuffer
  - [ ] Tizen
- [x] Windows

IDE:

- [x] Visual Studio 2022
- [ ] Visual Studio 2019
- [x] Visual Studio Code
- [ ] Visual Studio for Mac
- [x] Rider Windows
- [ ] Rider macOS

Relevant plugins:

**Comment by francoistanguay** [comment]
One more  thing important noting is that if you're trying Navigation from your ItemClicked, and you're using Navigation Extensions, you can simply set the Navigation.Request on the ListView itself and it will take care of everything:

https://github.com/unoplatform/Uno.Samples/blob/cae04df3bc67b9833e7b4e99623766eae9858638/reference/Commerce/src/Commerce/Views/DealsPage.xaml#L183
