### ISSUE TITLE
Win App crashed after installing Uno Cupertino Toolkit Library

### ISSUE THREAD

**Issue by ForkBug** [unoplatform/uno.toolkit.ui#1257]
## Current behavior

Win App crashed after installing Uno Cupertino Toolkit Library

## Expected behavior

Not crash

## How to reproduce it (as minimally and precisely as possible)

1. Create a new uno project.
2. Following the instructions of https://platform.uno/docs/articles/external/uno.toolkit.ui/doc/cupertino-getting-started.html?tabs=singleproj
3. Run WinAppSdk App. It will crash.

Repository to reproduce the bug: https://github.com/ForkBug/UnoAppBug

Nuget Package:

Package Version(s):

Affected platform(s):

[* ] Windows

IDE:

[* ] Visual Studio 2022

Relevant plugins:

**Comment by kazo0** [comment]
Hi @ForkBug!

I noticed you closed this issue shortly after opening it. Were you able to get around the issue or did you still need help with this?

**Comment by ForkBug** [comment]
Thanks, @kazo0 . Never mind, I copied some code from Uno.Gallary and it works now.
Btw, some of your introduction videos help me a lot in starting uno project development. Thank you!
