### ISSUE TITLE
[TabBar] Initial selected tab not displayed correctly 

### ISSUE THREAD

**Issue by Kunal22shah** [unoplatform/uno.toolkit.ui#1281]
## Current behavior
![image](https://github.com/user-attachments/assets/c7d6650e-3d68-4c0b-b415-22e3dc52addd)

```
		<utu:TabBar Grid.Row="2"
					VerticalAlignment="Bottom"
					uen:Region.Attached="True">
			<utu:TabBar.Items>
				<utu:TabBarItem uen:Region.Name="TBOne"
								Content="Tab One"
								IsSelected="True"/>
				<utu:TabBarItem uen:Region.Name="TBTwo"
								Content="Tab Two" />
				<utu:TabBarItem uen:Region.Name="TBThree"
								Content="Tab Three (User Control)" />
			</utu:TabBar.Items>
		</utu:TabBar>
		
```

## Expected behavior
![image](https://github.com/user-attachments/assets/1ae3c293-4383-43b9-b3d6-716439575f3d)

## How to reproduce it (as minimally and precisely as possible)

1. Create a new page with  TabBar control containing multiple TabBarItem elements.
2. Set `IsSelected="True"` on one of the TabBarItem elements to make it the initially selected tab.
3. Run the app and observe the initial state of the TabBar.

-  The tab with IsSelected="True" should display as selected when the page loads.

Nuget Package:

Package Version(s):

Affected platform(s):

- [ ] WebAssembly
- [ ] Android
- [ ] iOS
- [ ] macOS (AppKit)
- [ ] Mac Catalyst
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Linux Framebuffer
  - [ ] Tizen
- [ ] Windows

IDE:

- [ ] Visual Studio 2022
- [ ] Visual Studio 2019
- [ ] Visual Studio Code
- [ ] Visual Studio for Mac
- [ ] Rider Windows
- [ ] Rider macOS

Relevant plugins:

**Comment by kazo0** [comment]
@jeromelaban I'm wondering if [the fix](https://github.com/unoplatform/uno.toolkit.ui/pull/1288) should be backported. It's a side-effect of the recent template parent changes in Uno. So we'd only experience this issue if you are using latest Uno with Toolkit

**Comment by Xiaoy312** [comment]
the fix/workaround just add a fallback option, it can be safely added to any version of uno without any repercussion.
we should just simply backport it, so regardless the version of uno, it works, until we eventually break it again...

**Comment by jeromelaban** [comment]
Let's backport then!
