### ISSUE TITLE
[Uno.Themes/Uno.Toolkit.UI] Create a migration guide for previous controls that were moved or removed (related to #86)

### ISSUE THREAD

**Issue by jeromelaban** [unoplatform/uno.toolkit.ui#161]
It looks like BottomNavigationBar was only removed from Uno.Themes and never added to Toolkit.Ui
Was this a mistake? or is the control gone?

_Originally posted by @ConroyG in https://github.com/unoplatform/uno.toolkit.ui/issues/86#issuecomment-984949865_

**Comment by ConroyG** [comment]
It looks like the control was renamed to TabBar (or merged with it) 
To prevent it from acting as tabs use IsSelectable="False"

I havn't found the BottomNavigationBarBadge yet and i can't seem to resize Icons anymore

This probably just needs to be documented somewhere

**Comment by Xiaoy312** [comment]
@ConroyG 
BottomNavigationBar was replaced by TabBar, but it is not an exact 1:1 replacement
In the meant time, if you really need the badge and/or other customizabilities, you have two options:
- grab the old sources (control + style) from uno.themes; or
- grab the MaterialBottomTabBarItemStyle from this library, and modify to suit your needs
  > note that there is two copy of it, [one for ios+droid](https://github.com/unoplatform/uno.toolkit.ui/blob/main/src/library/Uno.Toolkit.Material/Styles/Controls/BottomTabBar.Mobile.xaml#L184) and [one for rest of the platforms](https://github.com/unoplatform/uno.toolkit.ui/blob/main/src/library/Uno.Toolkit.Material/Styles/Controls/BottomTabBar.xaml#L182): uwp, skia, wasm, etc...
