### ISSUE TITLE
Exported XAML with Card Control from Figma, breaking in UWP

### ISSUE THREAD

**Issue by rizaanlakay** [unoplatform/uno.toolkit.ui#166]
## Current behavior
Application crashes on startup on UWP head.

## Expected behavior
Load the Card Control in UWP Window.

## How to reproduce it (as minimally and precisely as possible)
Created a empty project with Material and Uno.Toolkit.
Opened the UNO Template in Figma and created a blank page. Dragged a Card Control onto it.
Exported the XAML and copied it into my project in VS.

## Environment

Nuget Package:

Package Version(s):

Affected platform(s):
- Windows

Visual Studio:
2022 Preview
[FinChoice.Mobi.zip](https://github.com/unoplatform/uno.toolkit.ui/files/7663251/FinChoice.Mobi.zip)

**Comment by agneszitte-nventive** [comment]
Related backport PR for stable 1.1 : https://github.com/unoplatform/Uno.Themes/pull/696
