### ISSUE TITLE
Padding not work for NavigationBar with MaterialNavigationBarStyle

### ISSUE THREAD

**Issue by HavenDV** [unoplatform/uno.toolkit.ui#180]
## How to reproduce it (as minimally and precisely as possible)
```xml
<utu:NavigationBar
    Padding="100,0,0,0"
    Content="Title"
    Style="{StaticResource MaterialNavigationBarStyle}"/>
```

## Environment
Uno.Material - 1.3.0-dev.4
Uno.Toolkit.UI - 1.3.0-dev.2
Uno.Toolkit.UI.Material - 1.3.0-dev.2

Affected platform(s):

- [x] UWP
- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renders for Xamarin.Forms
- [ ] Windows
- [ ] Build tasks

Visual Studio:

- [x] 2022 (version: 17.1 preview)

**Comment by jeromelaban** [comment]
## Note for contributors

Looks like the outer properties are not propagated completely through the presenter:

https://github.com/unoplatform/uno.toolkit.ui/blob/7f93c479ee86a5a455e0ca1314b8893fbab07859/src/library/Uno.Toolkit.Material/Styles/Controls/NavigationBar.Base.xaml#L45-L46

**Comment by kazo0** [comment]
I would've thought this would do the trick, unless I'm not forwarding the poperties properly here?

https://github.com/unoplatform/uno.toolkit.ui/blob/7f93c479ee86a5a455e0ca1314b8893fbab07859/src/Uno.Toolkit.UI/Controls/NavigationBar/NavigationBarPresenter.cs#L105
