### ISSUE TITLE
Crash in using MaterialNavigationViewStyle on WINUI Desktop 

### ISSUE THREAD

**Issue by jindal1979** [unoplatform/uno.toolkit.ui#185]
The crash is due to 

<contract4Present:Setter Target="RootGrid.(media:RevealBrush.State)" Value="PointerOver" />

RevealBrush is not available in Microsoft App SDK 1.0, which results in crash when we interact with NavigationViewItem.

**Comment by kazo0** [comment]
Thanks for the report @jindal1979! I will take a look and get a fix out ASAP
