### ISSUE TITLE
[Material][NavigationBar] - Title Alignment

### ISSUE THREAD

**Issue by kazo0** [unoplatform/uno.toolkit.ui#250]
M3 NavBar should be able to center- and left-align the title

https://m3.material.io/components/top-app-bar/overview

<img width="473" alt="image" src="https://user-images.githubusercontent.com/4793020/171447022-e9da4135-5c37-4c15-9d30-dd603530d736.png">

**Comment by NVLudwig** [comment]
@kazo0  Can we close this one now ?
