### ISSUE TITLE
AutoLayout prevents ListView child from scrolling

### ISSUE THREAD

**Issue by thierry-fortin1** [unoplatform/uno.toolkit.ui#272]
## Current behavior

The ListView control cannot scroll by itself like it normally should because it's parent is an AutoLayout.
(Left is a ListView in a Grid, right is a ListView in an AutoLayout)
![listviewscrollbug](https://user-images.githubusercontent.com/105242267/180257125-7269003d-abec-4324-90c4-cb7c84fb252a.gif)

## Expected behavior

Both should scroll correctly like the example on the left in the gif.

## How to reproduce it (as minimally and precisely as possible)

Open the sample App, try to scroll both ListViews with your scroll wheel.
Sample App: https://github.com/thierry-fortin1/ListViewScrollingBug 

## Environment

Nuget Package:
                PackageReference Include="Uno.WinUI" Version="4.4.13"
		PackageReference Include="Microsoft.Extensions.Logging" Version="6.0.0"
		PackageReference Include="Microsoft.WindowsAppSDK" Version="1.1.0"
		PackageReference Include="Microsoft.Windows.SDK.BuildTools" Version="10.0.22000.197"
		PackageReference Include="Microsoft.Extensions.Logging.Console" Version="6.0.0"
		PackageReference Include="Uno.Core.Extensions.Logging.Singleton" Version="4.0.1"
		PackageReference Include="Uno.Extensions.Navigation.Toolkit.WinUI" Version="2.0.0"
		PackageReference Include="Uno.Extensions.Reactive" Version="2.0.0"
		PackageReference Include="Uno.Extensions.Reactive.WinUI" Version="2.0.0"
		PackageReference Include="Uno.Toolkit.WinUI" Version="2.0.0"
		PackageReference Include="Uno.Toolkit.WinUI.Material" Version="2.0.0"

Package Version(s):

Affected platform(s):

- [X] iOS
- [X] Android
- [ ] WebAssembly
- [ ] WebAssembly renders for Xamarin.Forms
- [X] Windows
- [ ] Build tasks

Visual Studio:

- [ ] 2017 (version: )
- [ ] 2019 (version: )
- [ ] for Mac (version: )
- [X] 2022 Preview (version: 17.3.0 Preview 3.0)
- 
Relevant plugins:

- [ ] Resharper (version: )

**Comment by carldebilly** [comment]
This is not a bug. Explanation: the `<ScrollViewer />` **NEEDS** to be set with its alignment to `Stretch` to be able to scroll. That's not an issue, it's a spec.

Where it's hurting, it's because the default value of the attached property `utu:AutoLayout.PrimaryAlignment` is `Auto`, not `Stretch`, which gives the `<ListView />` a non-stretch alignment.

Demonstration: https://playground.platform.uno/#00a406ba

**Comment by takla21** [comment]
@carldebilly but if we wrap a `ScrollViewer` around a `ListView`, don't we lose virtualization? Which could cost us performance wise with a lot of items. https://platform.uno/docs/articles/controls/ListViewBase.html#internal-implementation
