### ISSUE TITLE
[Bottom Navigation Bar] Always masks content above it, even when FAB is not applyed to it

### ISSUE THREAD

**Issue by NVLudwig** [unoplatform/uno.toolkit.ui#273]
## Current behavior

When Layout includes a BottomTabBar a 28px height area above it spanning the entire width of the page is masked. Items in this area or scrolling through the area disappear behind this empty masking area.
![Screen Shot 2022-07-21 at 9 11 57 PM](https://user-images.githubusercontent.com/29584087/180341145-284a775f-0ff8-41d6-921b-8b1a9a86e03a.png)

## Expected behavior

items should be visible right up to the edge of the component as designed
![Screen Shot 2022-07-21 at 9 13 46 PM](https://user-images.githubusercontent.com/29584087/180340706-0f74623b-10b7-42bc-a63a-049095195b72.png)

## How to reproduce it (as minimally and precisely as possible)

In Figma place component in layout with an adjacent item above it
Run the Uno plugin
Observe the preview tab

## Environment

Nuget Package:

Package Version(s):

Affected platform(s):

- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renders for Xamarin.Forms
- [ ] Windows
- [ ] Build tasks

Visual Studio:

- [ ] 2017 (version: )
- [ ] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

## Anything else we need to know?

We knew this was happening when a FAB TabBarItem is included in the BottomTabBar, but since it actually happening in all cases involving the BottomTabBar (aka Bottom Navigation) I'm creating a issue to bump this up the priority list.

**Comment by kazo0** [comment]
Caused by  https://github.com/unoplatform/uno/issues/7393
