### ISSUE TITLE
Add Badge Property to TabBarItem

### ISSUE THREAD

**Issue by kazo0** [unoplatform/uno.toolkit.ui#274]
Add a Badge property to TabBarItem to display an optional badge on the control. See [Uno Material Figma file](https://www.figma.com/file/trM3i5qUPmFBcnxWXXmnuF/Uno-Platform-Material-Toolkit-R2?node-id=1462%3A33235) 

![Image](https://user-images.githubusercontent.com/4793020/186535388-469452c4-4eb6-4ebe-a5e2-a2cc26f08731.png)

![Image](https://user-images.githubusercontent.com/4793020/186535118-93b01db4-a8d3-4679-b54d-b87e58787240.png)

**Comment by agneszitte-nventive** [comment]
Commit to the work I did with InfoBadge if needed later on, as InfoBadge is not available yet in WinUI3 :
https://github.com/unoplatform/uno.toolkit.ui/commit/c935919b2c390014dd8509cc50e16b1549511ffa
