### ISSUE TITLE
[Windows] Drawer Flyout Presenter Crash

### ISSUE THREAD

**Issue by Soap-141** [unoplatform/uno.toolkit.ui#277]
## Current behavior

It crashes when pressing on a button flyout with `FlyoutPresenterStyle`.

Debug Output:
An unhandled exception of type 'System.AccessViolationException' occurred in Microsoft.WinUI.dll
Attempted to read or write protected memory. This is often an indication that other memory is corrupt.

Call Stack:
```
 	[Managed to Native Transition]	
 	Microsoft.WinUI.dll!ABI.Microsoft.UI.Xaml.Media.IVisualTreeHelperStaticsMethods.GetOpenPopups(WinRT.IObjectReference _obj, Microsoft.UI.Xaml.Window window)	Unknown
 	Uno.Toolkit.WinUI.dll!Uno.Toolkit.UI.Controls.DrawerFlyoutPresenter.FindHostPopup()	Unknown
 	Uno.Toolkit.WinUI.dll!Uno.Toolkit.UI.Controls.DrawerFlyoutPresenter.OnApplyTemplate()	Unknown
 	Microsoft.WinUI.dll!Microsoft.UI.Xaml.FrameworkElement.Microsoft.UI.Xaml.IFrameworkElementOverrides.OnApplyTemplate()	Unknown
 	Microsoft.WinUI.dll!ABI.Microsoft.UI.Xaml.IFrameworkElementOverrides.Do_Abi_OnApplyTemplate_2(System.IntPtr thisPtr)	Unknown
 	[Native to Managed Transition]	
 	[Managed to Native Transition]	
 	Microsoft.WinUI.dll!ABI.Microsoft.UI.Xaml.IApplicationStaticsMethods.Start(WinRT.IObjectReference _obj, Microsoft.UI.Xaml.ApplicationInitializationCallback callback)	Unknown
 	Microsoft.WinUI.dll!Microsoft.UI.Xaml.Application.Start(Microsoft.UI.Xaml.ApplicationInitializationCallback callback)	Unknown
>	DrawerFlyoutPresenterSample.Windows.dll!DrawerFlyoutPresenterSample.Program.Main(string[] args) Line 31	C#

```

## Expected behavior

It should not crash when pressing on a button flyout with `FlyoutPresenterStyle`.

![Animation_51](https://user-images.githubusercontent.com/57812285/182454827-8a4fc539-c5ff-495c-aa71-6caa8f72fc40.gif)

## How to reproduce it (as minimally and precisely as possible)

1. Download [DrawerFlyoutPresenterSample.zip](https://github.com/unoplatform/uno.toolkit.ui/files/9245030/DrawerFlyoutPresenterSample.zip)
2. Start Solution with VS 2022 Preview 6
3. Start Windows (WinUI) Project
4. Click on Test button
5. Notice crash

## Environment

Nuget Package:

- Uno.Toolkit.WinUI
- Uno.Toolkit.WinUI.Material
- Uno.Material.WinUI

Package Version(s):

- 2.3.0-dev.5
- 2.3.0-dev.5
- 2.3.0-dev.4

Affected platform(s):

- [ ] iOS
- [ ] Android
- [ ] ~~WebAssembly~~
- [ ] ~~WebAssembly renders for Xamarin.Forms~~
- [x] Windows
- [ ] ~~Build tasks~~

Visual Studio:

- [ ] ~~2017 (version: )~~
- [ ] ~~2019 (version: )~~
- [x] 2022 (version: 17.2.6)
- [x] 2022 (version: 17.3.0 Preview 6.0)
- [ ] ~~for Mac (version: )~~

Relevant plugins:

- [ ] ~~Resharper (version: )~~

## Anything else we need to know?

I used this [documentation](https://github.com/unoplatform/uno.toolkit.ui/blob/main/doc/controls/DrawerFlyoutPresenter.md).

**Comment by jeromelaban** [comment]
Thanks for the report. As you're getting a crash, can you provide the full crash stack trace ?

**Comment by Soap-141** [comment]
@jeromelaban Done.
