### ISSUE TITLE
We need a recipe for customizing keyboard enter key behavior

### ISSUE THREAD

**Issue by takla21** [unoplatform/uno.toolkit.ui#280]
## What would you like to be added:

We need to have a way to customize the native keyboard enter key behavior so we could for instance implement inter `Textbox` and/or `PasswordBox` navigation. Ideally it would look something like this:

```xmal

<TextBox Text={Binding Username}
               keyboardBehavior.NextControl={Binding ElementName=PasswordField} />

<PasswordBox x:Name="PasswordField"
                        Text={Binding Password}
                        keyboardBehavior.EnterCommand={Binding Login}
                        keyboardBehavior.DismissKeyboardOnEnter="True" />

<Button Content="Login" 
              Command={Binding Login} />

```

So we could have a behavior that could do:
- Redirect focus on another control after the user press the keyboard enter key.
- Execute a command after the user press the keyboard enter key.
- Close the keyboard after the user press the keyboard enter key.

## Why is this needed:

We need this for one of our Uno.WinUI project.

## For which Platform:

- [x] iOS
- [x] Android
- [ ] WebAssembly
- [ ] WebAssembly renders for Xamarin.Forms
- [x] Windows (optional)
- [ ] Build tasks

**Comment by jeanplevesque** [comment]
@kazo0 You could leverage code from Nventive.View for this.
https://github.com/nventive/Nventive.View/tree/master/src/View.Uno/Extensions/TextBox

**Comment by Xiaoy312** [comment]
# InputExtensions
- AutoDismiss (bool): dismiss keyboard on enter
- AutoFocusNext (bool): focus next focusable element on enter
- AutoFocusNextTarget (UIElement): element to focus on enter
- EnterCommand (ICommand): command to execute on enter

note1: Keyboard dismiss can happen when either AutoDismiss or EnterCommand is set
note2: Auto focus is enabled by either AutoFocusNext and/or AutoFocusNextTarget, the AutoFocusNextTarget or next focusable element will be in focus

---
note: on android, the KeyUp event is currently not triggering, even with ImeOptions set. we will need a workaround for this...
  ^ see: https://platform.uno/docs/articles/features/pointers-keyboard-and-other-user-inputs.html
  ^ see-also: https://developer.android.com/training/keyboard-input/commands
