### ISSUE TITLE
Add Command/CommandParameter Extensions for ListViewBase

### ISSUE THREAD

**Issue by kazo0** [unoplatform/uno.toolkit.ui#282]
Add the ability to attach Command/CommandParameter properties to a ListView, this would allow the click of each item in the list to execute the specified ICommand.

**Comment by Xiaoy312** [comment]
CommandParameter would make no sense on the ListView level; unless we are trying to differentiate between multiple ListView that share the same command..?
It is better to just send the clicked item back as parameter (`ICommand.Execute(object parameter)`).
