### ISSUE TITLE
[Windows] Issues with DrawerControl (Cannot find a Resource with the Name/Key TrueToVisible | GestureInterceptorMargin was not found)

### ISSUE THREAD

**Issue by FrozDark** [unoplatform/uno.toolkit.ui#290]
## Current behavior
Using DrawerControl in windows throws COMException with "Cannot find a Resource with the Name/Key TrueToVisible".
By the name of resource I realized that it's a simple visibility converter. After manually adding it an another COMException with message "The property 'GestureInterceptorMargin' was not found in type 'Uno.Toolkit.UI.DrawerControl'" is thrown
Same issue with GTK but allowing an app work without gesture support there https://github.com/unoplatform/uno/issues/9487

## Expected behavior
Working control with no issues and exceptions

## How to reproduce it (as minimally and precisely as possible)
I could attach repro if needed

## Environment

Nuget Package:
```
<PackageReference Include="CommunityToolkit.WinUI" Version="7.1.2" />
<PackageReference Include="CommunityToolkit.WinUI.UI.Controls" Version="7.1.2" />
<PackageReference Include="CommunityToolkit.WinUI.UI.Controls.DataGrid" Version="7.1.2" />
<PackageReference Include="Mapsui" Version="4.0.0-build.3855" />
<PackageReference Include="Mapsui.ArcGIS" Version="4.0.0-build.3855" />
<PackageReference Include="Mapsui.Extensions" Version="4.0.0-build.3855" />
<PackageReference Include="Microsoft.WindowsAppSDK" Version="1.2.220727.1-experimental1" />
<PackageReference Include="Microsoft.Windows.SDK.BuildTools" Version="10.0.25179-preview" />
<PackageReference Include="Microsoft.Extensions.Logging.Console" Version="7.0.0-preview.7.22375.6" />
<PackageReference Include="SkiaSharp.Views.WinUI" Version="2.88.1-preview.108" />
<PackageReference Include="Uno.Core.Extensions.Logging.Singleton" Version="4.0.1" />
<PackageReference Include="Uno.Toolkit.WinUI" Version="2.3.0-dev.6" />
<PackageReference Include="Uno.Toolkit.WinUI.Material" Version="2.3.0-dev.6" />
<PackageReference Include="Uno.WinUI" Version="4.5.0-dev.523" />
```

Package Version(s):

Affected platform(s):

- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renders for Xamarin.Forms
- [X] Windows
- [ ] Build tasks

Visual Studio:

- [ ] 2017 (version: )
- [ ] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by Xiaoy312** [comment]
Sorry for the late update.

The key is actually `MaterialTrueToVisible` coming from themes (package: Uno.Material). This was previously keyed as just `TrueToVisible`. In the toolkit sample app, we have the workaround applied to use the ancient key hence why it is not caught here...
We will be doing a review of converter resources and the likes soon, to address this kind of problem.

 In the mean time, you can redefine the same resources highlighted here: https://github.com/unoplatform/Uno.Themes/blob/release/stable/2.4/src/library/Uno.Material/Styles/Application/Common/Converters.xaml#L5-L45
without the said prefix in your app.
