### ISSUE TITLE
Port BindableVisualState

### ISSUE THREAD

**Issue by kazo0** [unoplatform/uno.toolkit.ui#306]
https://github.com/nventive/Nventive.View/blob/master/doc/BindableVisualState.md

**Comment by Xiaoy312** [comment]
to merge with: https://github.com/unoplatform/uno.extensions/tree/main/src/Uno.Extensions.Reactive.UI/Utils/ViewDebugger

**Comment by Xiaoy312** [comment]
summary: Provides a set of attached properties for adding custom visual state, and debugging visual state of a `Control`.
contract:
```
VisualStateGroupExtensions
	.CustomGroup1State = (string)		// Sets the state to enter for the custom VisualStateGroup
	.CustomGroup2State = (string)		// Sets the state to enter for the custom VisualStateGroup 2
	.CustomGroup3State = ...
	.CustomGroup4State = ...

	.EnableDebugger = (bool)			// flag to active: AvailableVisualStates and VisualStates
	.AvailableVisualStates = (string)	// [get-only] list the available visual-states defined in the ControlTemplate or the template root.
		^ eg: "CommonStates: Normal, PointerOver, Pressed, Disabled; FocusStates: Focused, PointerFocused, Unfocused;"
	.VisualStates = (string)			// semi-colon-separated list of active state in each of defined VisualStateGroup; can be set to force a control to enter specific state
		^ eg: "Disabled;Unfocused", "Disabled" (only update the CommonStates)
```

**Comment by dr1rrb** [comment]
Humm I think that we should not merge booth.

The `ViewDebugger` is something that should removed in release build like the `System.Diagnostics.Debug` (and we should probably flag all members with the `[Conditional("DEBUG")]` attribute (like the `Debug` class).

**Comment by francoistanguay** [comment]
Could we still merge into same class but different property named .NameOverride or .DebugName that is available in debug only?

Would be less clutter into single class with similar behaviour

**Comment by francoistanguay** [comment]
And don't know why we call this a custom state?

**Comment by francoistanguay** [comment]
> Could we still merge into same class but different property named .NameOverride or .DebugName that is available in debug only?
> 
> Would be less clutter into single class with similar behaviour

Actually the debug is overkill and is I different from any hard coded property in xaml sinks keep the single bendable property and drop the debugger stuff
