### ISSUE TITLE
Title and other NavigationBar content disappears from all pages when using QLPreviewController to open a file

### ISSUE THREAD

**Issue by Marc-Antoine-Soucy** [unoplatform/uno.toolkit.ui#307]
## Current behavior

After I open a pdf in an app using Uno.Extensions, all the content on the NavigationBar disappears from all pages.

## Expected behavior

The NavigationBar should not be change after opening and closing a file using QLPreviewController 

## Environment

Nuget Package (in app with bug):
    "Uno.WinUI" Version="4.5.0-dev.671" 
    
    "Uno.WinUI.RemoteControl" Version="4.5.0-dev.671" Condition="'$(Configuration)'=='Debug'" 
    "Uno.UI.Adapter.Microsoft.Extensions.Logging" Version="4.3.6" 
    "Microsoft.Extensions.Logging" Version="6.0.0" 
    "Uno.Extensions.Logging.OSLog" Version="1.4.0" 
   "Uno.Core" Version="4.0.1" 
    "Uno.Material.WinUI" Version="2.3.0-dev.10" 
    "Uno.Toolkit.WinUI.Material" Version="2.3.0-dev.12" 
    "Uno.Toolkit.WinUI" Version="2.3.0-dev.12" 
    "Uno.SourceGenerationTasks" Version="4.1.0" 

    "Uno.Extensions.Authentication" Version="2.2.0-dev.196" 
    "Uno.Extensions.Configuration" Version="2.2.0-dev.196" 
   "Uno.Extensions.Core" Version="2.2.0-dev.196" 
    "Uno.Extensions.Hosting" Version="2.2.0-dev.196" 
    "Uno.Extensions.Hosting.WinUI" Version="2.2.0-dev.196" 
    "Uno.Extensions.Http" Version="2.2.0-dev.196" 
    "Uno.Extensions.Http.Refit" Version="2.2.0-dev.196" 
    "Uno.Extensions.Localization.WinUI" Version="2.2.0-dev.196" 
    "Uno.Extensions.Logging.Serilog" Version="2.2.0-dev.196"
    "Uno.Extensions.Logging.WinUI" Version="2.2.0-dev.196" 
    "Uno.Extensions.Navigation.Toolkit.WinUI" Version="2.2.0-dev.196" 
    "Uno.Extensions.Navigation.WinUI" Version="2.2.0-dev.196" 
    "Uno.Extensions.Navigation" Version="2.2.0-dev.196" 
    "Uno.Extensions.Serialization" Version="2.2.0-dev.196" 
    "Uno.Extensions.Serialization.Refit" Version="2.2.0-dev.196" 
    "Uno.Extensions.Reactive" Version="2.2.0-dev.196" 
    "Uno.Extensions.Reactive.WinUI" Version="2.2.0-dev.196" 
Package Version(s):

Affected platform(s):

- [X] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renders for Xamarin.Forms
- [ ] Windows
- [ ] Build tasks

Visual Studio:

- [ ] 2017 (version: )
- [X] 2022 (version: 17.2.6)
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

## Anything else we need to know?

I tried to reproduce it in this sample, but it doesnt happen.
[OpenPDFIOSHeader.zip](https://github.com/unoplatform/uno.toolkit.ui/files/9472473/OpenPDFIOSHeader.zip)

**Comment by Marc-Antoine-Soucy** [comment]
I know in the sample attempt, you don't really open a pdf, but doing the same thing in the real app, the bug still happens.

**Comment by agneszitte-nventive** [comment]
From @kazo0:

> The issue is coming from somewhere in the flow of the Toolkit [NativeFramePresenter ](https://github.com/unoplatform/uno.toolkit.ui/blob/main/src/Uno.Toolkit.UI/Controls/NavigationBar/NativeFramePresenter.iOS.cs)+ [iOS NavigationBarRenderer](https://github.com/unoplatform/uno.toolkit.ui/blob/main/src/Uno.Toolkit.UI/Controls/NavigationBar/NavigationBarRenderer.iOS.cs) + [iOS NavigationBarNavigationItemRenderer](https://github.com/unoplatform/uno.toolkit.ui/blob/main/src/Uno.Toolkit.UI/Controls/NavigationBar/NavigationBarNavigationItemRenderer.iOS.cs). Specifically, the NavigationBarNavigationItemRenderer is not calling Render when we are navigating back from the native QLPreviewController. Note, this is happening only within the actual Isaac iOS application. A standalone sample is not reproducing the issue. Steps are:

>Login (anything in the first field), use "nvntcaa" for login and password
Tap on More in the Bottom TabBar
Tap on Documents
Tap on the Document listed
Nav bar from the PDF
Notice NavBar is blank

**Comment by agneszitte-nventive** [comment]
The issue seems related to the TabBar control (maybe a navigation issue?)

Here in the attachment, you can see [with the same code on both pages] :
- NavBar outside of a TabBar inside a page (not able to reproduce the issue)
![017cdaceffd8ccd47f29347953ed306b](https://user-images.githubusercontent.com/16295702/190437289-815bb814-0aee-43e8-86c2-a25ea12669d1.gif)

- NavBar inside the page content of one of the TabBarItems (able to reproduce the issue)
![227583f1cf20982734fa16b44c038d2c (2)](https://user-images.githubusercontent.com/16295702/190437194-2ccb5923-3a0f-45f8-985b-f998f5f6aaf3.gif)

**Comment by Xiaoy312** [comment]
<details>
<summary>debug note</summary>

```
## sequence of events v2
=== app launch ===
@xy NavigationBarHelper::PageCreated: {PageViewController (MainPage)}
@xy Renderer<TElement,TNative>.OnNativeChanged() // _native: {<UINavigationItem: 0x7f879de3d370>} (hash=-1646023433)
@xy NBNIRenderer::Initialize(): {<UINavigationItem: 0x7f879de3d370>} \ (null)
@xy NBNIRenderer::Render(): {<UINavigationItem: 0x7f879de3d370>} \ (null)
@xy NBNIRenderer::Render(): {<UINavigationItem: 0x7f879de3d370>} \ (null)
@xy NavigationBarHelper::PageWillAppear: {PageViewController (MainPage)}
@xy NavigationBarHelper::PageCreated: {PageViewController (HomePage)}
@xy Renderer<TElement,TNative>.OnNativeChanged() // _native: {<UINavigationItem: 0x7f879ded12d0>} (hash=-1645384361)
@xy NBNIRenderer::Initialize(): {<UINavigationItem: 0x7f879ded12d0>} \ "Hello World!"
@xy NBNIRenderer::Render(): {<UINavigationItem: 0x7f879ded12d0>} \ "Hello World!"
@xy NBNIRenderer::Render(): {<UINavigationItem: 0x7f879ded12d0> title='Hello World!'} \ "Hello World!"
@xy NavigationBarHelper::PageWillAppear: {PageViewController (HomePage)}
@xy NavigationBarHelper::PageWillAppear: navbar=-92200754, native=-1623200455
@xy Renderer<TElement,TNative>.OnNativeChanged() // _native: {Uno.UI.Controls.UnoNavigationBar} (hash=-1623200455)
@xy NBNIRenderer::Render(): {<UINavigationItem: 0x7f879ded12d0> title='Hello World!'} \ "Hello World!"

=== to pdf ===
@xy NavigationBarHelper::PageWillDisappear: {PageViewController (MainPage)}
@xy Renderer<TElement,TNative>.OnNativeChanged() // _native: (null) (hash=)
@xy NavigationBarHelper::PageWillDisappear: {PageViewController (HomePage)}
@xy NavigationBarHelper::PageDidDisappear: {PageViewController (HomePage)}
@xy NavigationBarHelper::PageDidDisappear: {PageViewController (MainPage)}

== back from pdf ===
@xy NavigationBarHelper::PageWillAppear: {PageViewController (MainPage)}
@xy NavigationBarHelper::PageWillAppear: navbar=-92200754, native=425429157
@xy Renderer<TElement,TNative>.OnNativeChanged() // _native: {Uno.UI.Controls.UnoNavigationBar} (hash=425429157)
@xy NavigationBarHelper::PageWillAppear: {PageViewController (HomePage)}
@xy NavigationBarHelper::PageWillAppear: navbar=-92200754, native=-1623200455
@xy Renderer<TElement,TNative>.OnNativeChanged() // _native: {Uno.UI.Controls.UnoNavigationBar} (hash=-1623200455)

for context, the original should-probably-not-be-named app has the following page layout: // roughly~
	  MainPage: has no NavBar (shell/root view)
	      HomePage: contains NavBar
	      PageTwo: contains NavBar
	      Page3: contains NavBar
	      ...

whats interesting in the above logs is ... on the back navigation from the pdf viewer:
	  @xy NavigationBarHelper::PageWillAppear: {PageViewController (MainPage)}
	  @xy NavigationBarHelper::PageWillAppear: navbar=-92200754, native=425429157
	  @xy NavigationBarHelper::PageWillAppear: {PageViewController (HomePage)}
	  @xy NavigationBarHelper::PageWillAppear: navbar=-92200754, native=-1623200455

in the "app launch" part, we also have PageViewController called twice for MainPage+HomePage, 
    ^ but the native instance setup only happens for HomePage because it owns the NavBar
    ^ and not for MainPage

on the back navigation from pdf, MainPage, this times, gets setup with a NavBar, the one from HomePage
    ^ this is because the _associated_ navbar lookup is naively drills the visual-tree from the page
    ^ and not stopping at the page-to-frame barrier as it should

here is the flatten hierarchy between MainPage and HomePage's NavBar:
	  MainPage > AutoLayout > Border > Grid#PART_RootGrid > Grid > Grid > 
	  FrameView > Frame#NavigationFrame > NativeFramePresenter > UIView > UIView > UIView > 
	  HomePage > Grid > NavigationBar
```
</details>
