### ISSUE TITLE
feat: LoadingView

### ISSUE THREAD

**Issue by Xiaoy312** [unoplatform/uno.toolkit.ui#308]
todo

**Comment by Xiaoy312** [comment]
from onenote:
- Context
    - Extended Splash Screen
    - Unify multiple FeedView(s) into single loading indicator

- Unknowns
    - Handle Refreshing?
    - UI Setup
        ```
        RefreshContainer
            LoadingView
                FeedView 1
                FeedView 2

        -- OR --

        LoadingView
            RefreshContainer
                FeedView 1
                FeedView 2
        RefreshButton
        ```

- Loading View
- Uno.Toolkit (non ui)
    ```cs
    interface ILoadable
        bool IsLoading { get; }
        event IsLoadingChanged;
    interface IAsyncCommand : ILoadable
        CanExecute/Changed
        Execute
    AsyncCommand
    ```
- Uno.Toolkit.UI
    ```
    CompositeLoadableSource
        .Add(UIElement)
            ElementName resolving
            Parses Visual Tree / Find/Attach to Parent
            Ancestral Binding?
    ```

- Uno.Extensions.Reactive would take dependency on Uno.Toolkit
- LoadingView
    ```
    Source : ILoadable { get; set; }
    Loading State
    Executing State
    Loaded State
    Default (Loading)
    ```

**Comment by Xiaoy312** [comment]
```
namespace Uno.Toolkit.Core // non-ui
    ^ namespace & package-id are to be confirmed
    interface ICommand // just here for reference
        bool CanExecute(object);
        void Execute(object);
        event EventHandler CanExecuteChanged;
    interface ILoadable
        bool IsExecuting { get; }
        event EventHandler IsLoadingChanged;
    interface IAsyncCommand : ICommand, IAsyncCommand, INotifyPropertyChanged
    class AsyncCommand : IAsyncCommand, IDisposable
        // impl to be brought over from Uno.Extensions
namespace Uno.Toolkit.UI
    class LoadingView : Control
        ILoadable Source { get; set; } // dp
        "ContentStates" visual-states: "Initial", "Loading", "Loaded"
    class CompositeLoadableSource : DependencyObject, ILoadable
        IList<ILoadable> Sources { get; } // dp, [ContentProperty]

LoadingView.Source examples:
    <CompositeLoadableSource AutoDiscoverSources="True" />
    ---
    <CompositeLoadableSource>
        <LoadableSource Source="{Binding ElementName=FeedView1}" />
        <LoadableSource Source="{Binding ElementName=FeedView2}" />
    ---
    <IocLoadableSource />
    ...

    <rx:FeedView toolkit:LoadingViewExtensions.Owner="{toolkit:AncestralBinding Type={toolkit:LoadingView}}">
```

**Comment by francoistanguay** [comment]
I dont think we should reuse ICommand and instead keep the IAsyncCommand we have now.. And are those methods Async in reactive? @dr1rrb  Do we also need a dependency on IDispatcher if we bring in the implementation? 
Maybe we should leave implementation in Reactive for now and force our apps to use a generated command in a VM for App Bootstrapping as well

And you should align IsExecuting/IsExecutingChanged

I also dont see why we should have 3 states and differentiage between Initial/Loading... Should be Executing/Done or Loading/Loaded

**Comment by Xiaoy312** [comment]
we need to reuse ICommand, because that is the interface accepted by [Button.Command](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.primitives.buttonbase.command?view=winrt-22621)
we can maybe just leave IAsyncCommand and its concrete class in uno.extensions
to my understanding, LoadingView only need to know about the "loading" state, not the implementation details
which means just having ILoadable would suffice

**Comment by francoistanguay** [comment]
Ah I missed you were just putting ICommand for reference. Get it now. We can indeed leave commands for now in Reactive and see how it goes!

**Comment by francoistanguay** [comment]
Not sure CompositeLoadableSource and LoadableSource shoulr have a Source suffix.

ANd should LoadableSource.Source be caled Element?

**Comment by dr1rrb** [comment]
1. Current implementation of AsyncCommand has a strong dependency on feeds, it will be much easier to create another implementation if we need it.
2. We don't need `IDispatcher`: this interface makes sense only for non-UI related classes that have to exceptionally execute something on the UI thread (e.g. `MessageDialog`). Here we have direct access to UI elements, we just need to capture the dispatcher at the right time.
3. Agree that we should have only Loading/Loaded states.
4. For the `CompositeLoadableSource.Add(UIElement)`, I think that we should instead have `CompositeLoadableSource.Add(ILoadable)`. And to allow XAML declaration using  `ElementName` we will indeed need something like a `LoadableElement` that has a databindable `Source` (or `Element`) and which implements `ILoadable` (only proxy to the lazy `Source`)
