### ISSUE TITLE
DrawerFlyoutPresenter is in the wrong namespace

### ISSUE THREAD

**Issue by kazo0** [unoplatform/uno.toolkit.ui#311]
DrawerFlyoutPresenter is currently under the `Uno.Toolkit.UI.Controls` namespace, which differs from all other controls that are in the `Uno.Toolkit.UI` namespace.

This would require two `xmlns` declarations in your xaml:
`xmlns:utu="using:Uno.Toolkit.UI"`
`xmlns:utuc="using:Uno.Toolkit.UI.Controls"`

**Comment by Xiaoy312** [comment]
you dont really need to reference the xmlns, since we mostly just use by resource-key
but it is annoying...
