### ISSUE TITLE
Bindings don't work inside an AutoLayout element

### ISSUE THREAD

**Issue by Suriman** [unoplatform/uno.toolkit.ui#315]
## Current behavior

Create a control style that uses an AutoLayout element to wrap other composite controls, Control bindings to composite controls don't work.

## Expected behavior

The bindings should be work fine.

## How to reproduce it (as minimally and precisely as possible)

Open the attached project, compile and run it. On the main page, display two TestControl instance, made up of two TextBlocks and a Button. The first instance uses an AutoLayout element to wrap the composite controls, and the second instance uses a StackPanel element. Only bindings work on the second instance.

## Workaroud

Use a LangVersion greater or equal than 10.0

## Works on UWP/WinUI

Yes

## Environment

NuGet package(s): Uno.WinUI
NuGet package version(s): Uno.WinUI 4.4.20

## Affected platform(s):

- [x] iOS
- [x]  Android
- [x] macOS
- [x] WPF
- [x] WebAssembly

Visual Studio:

- [x] 2022 (version: 17.3.3)

Relevant plugins:

N/A

## Anything else we need to know?

See .rar attached.
[AutoLayoutBindings.zip](https://github.com/unoplatform/uno.toolkit.ui/files/9547134/AutoLayoutBindings.zip)

**Comment by carldebilly** [comment]
The bug is related to the TemplatedParent which is not correctly resolved at runtime because of the way items are handled by the control.

Here's a workaround:
``` xml
                        <utu:AutoLayout Orientation="Vertical" Spacing="4" DataContext="{Binding RelativeSource={RelativeSource Mode=TemplatedParent}, Mode=OneWay}">
                            <TextBlock Text="{Binding Caption, Mode=OneWay, FallbackValue='Binding failure'}" />
                            <TextBlock Text="{Binding Value, Mode=OneWay, FallbackValue='Binding failure'}" />
                            <Button Command="{Binding Command, Mode=OneWay}" Content="Change Text" />
                        </utu:AutoLayout>
```

/fyi @jeromelaban

**Comment by jeromelaban** [comment]
Indeed, this is related to https://github.com/unoplatform/uno/issues/1621. Let's close this issue and track the other one as needed.

**Comment by Suriman** [comment]
Thank you very much!
