### ISSUE TITLE
AutoLayout is not redrawing controls in WPF.

### ISSUE THREAD

**Issue by Suriman** [unoplatform/uno.toolkit.ui#343]
## Current behavior

Using the AutoLayout control in WPF head if the window is resized horizontally the controls are redrawn but if it is done vertically the controls are not redrawed.

The bug is independent of the style applied.

## Expected behavior

The controls are redrawn correctly after a vertical resize.

## How to reproduce it (as minimally and precisely as possible)

An application is created with the AutoLayout control.

## Environment

NuGet package(s): 

Uno.WinUI 4.5.9, 
Uno.Material.WinUI 2.3.0, 
Uno.Toolkit.WinUI 2.3.0

Affected platform(s):

- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renders for Xamarin.Forms
- [X] Windows 10.0.19044
- [X] WPF
- [ ] Build tasks

Visual Studio:

- [ ] 2017 (version: )
- [ ] 2019 (version: )
- [X] 2022 (version: 17.3.4)
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

## Anything else we need to know?

See the attached file.
[AutoLayoutNotRedrawInWPF.zip](https://github.com/unoplatform/uno.toolkit.ui/files/9665957/AutoLayoutNotRedrawInWPF.zip)

**Comment by ADD-Eugenio-Lopez** [comment]
I reproduce the solution with the last template and nugets and everything runs correctly, therefore this issue can be closed.

**Comment by jeromelaban** [comment]
@ADD-Eugenio-Lopez thanks for the update!
