### ISSUE TITLE
[Android] SafeArea for SoftInput Not Working Correctly

### ISSUE THREAD

**Issue by Soap-141** [unoplatform/uno.toolkit.ui#345]
## Current behavior

Keyboard goes on top of safe area and the content is not getting pushed up.

![Animation_60](https://user-images.githubusercontent.com/57812285/193664065-80ba8f63-cfae-44c8-82c6-78c053c323c6.gif)

## Expected behavior

Keyboard push safe area content and doesn't go over it.

## How to reproduce it (as minimally and precisely as possible)

1. Download [ReproSafeArea.zip](https://github.com/unoplatform/uno.toolkit.ui/files/9700428/ReproSafeArea.zip)
2. Configure the keyboard height of your device to Extra Tall so it goes over the safe area (See GIF bellow)
3. Start Android Project click on a field that opens the keyboard
4. Notice keyboard is on top the CheckBox when it should not

![Animation_59](https://user-images.githubusercontent.com/57812285/193664777-d92d21f0-8098-4262-aced-a0458bc65674.gif)

## Environment

Nuget Package:
- Uno.Toolkit.WinUI
- Uno.WinUI

Package Version(s):
- 2.4.0-dev.23
- 4.6.0-dev.515

Affected platform(s):

- [ ] ~~iOS~~
- [x] Android
- [ ] ~~WebAssembly~~
- [ ] ~~WebAssembly renders for Xamarin.Forms~~
- [ ] ~~Windows~~
- [ ] ~~Build tasks~~

Visual Studio:

- [ ] ~~2017 (version: )~~
- [ ] ~~2019 (version: )~~
- [x] 2022 (version: 17.3.5)
- [ ] ~~for Mac (version: )~~

Relevant plugins:

- [ ] ~~Resharper (version: )~~

**Comment by jeromelaban** [comment]
This looks like a good example of scenario to document. in this case. You'll likely want to add padding to a control (like a `Grid`) around the `ScrollViewer`, not on the `ScrollViewer` itself. This will reduce the size of the `ScrollViewer`, therefore allowing it to scroll.

The best way to test this is to set the padding on the control to simulate the conditions when the keyboard is up. It's likely that in this case, the padding won't change anything.

**Comment by kazo0** [comment]
[Updates have been made](https://github.com/unoplatform/uno.toolkit.ui/pull/374) in SafeArea to include a ScrollViewer when used as a wrapping panel, as well as [updated docs for usage scenarios](https://github.com/unoplatform/uno.toolkit.ui/blob/main/doc/controls/SafeArea.md#using-insetmasksoftinput-for-on-screen-keyboards)
