### ISSUE TITLE
TimeSpan attached property crashes the app in Release x64

### ISSUE THREAD

**Issue by artemious7** [unoplatform/uno.toolkit.ui#377]
## Current behavior
When setting a `TimeSpan` attached property in Release mode, the app crashes with the message:
```
Windows.UI.Xaml.Markup.XamlParseException: 'The text associated with this error code could not be found.

Cannot deserialize XBF metadata property list as 'Time' was not found in type 'Repro.Properties'. [Line: 0 Position: 0]'
```

## Expected behavior
The attached property is set without crashing.

## How to reproduce it (as minimally and precisely as possible)
- create a blank UWP project
- add the Uno.Toolkit.UI package
- create an attached property of type TimeSpan
- set the property on a control
- run the app in Release x64 mode
- see the app crashes (in Debug mode and Release x86 it works fine)
[App11.zip](https://github.com/unoplatform/uno.toolkit.ui/files/9850844/App11.zip)

## Workaround
Use `Nullable<TimeSpan>` instead of `TimeSpan`

## Environment

Nuget Package:
Uno.Toolkit.UI

Package Version(s):
all

Affected platform(s):

- Windows

OS version:
Edition	Windows 11 Pro
Version	21H2
OS build	22000.1098

Visual Studio:

- 2022 (version: 17.4.0 preview 2.1)
- 2022 (version: 17.2.6)

Relevant plugins:
none

**Comment by Xiaoy312** [comment]
this is unrelated to uno, more of a windows limitation
this is unrelated to toolkit neither, more of a generation xaml problem

we are trying to set a attached dp of type `TimeSpan` in xaml like so: // yes, the attached dp is defined propertly
```
<TextBox r:Properties.Time="0:0:0.100" />
````
while it may be possible to do so in the debug or release x86, release x64 throws on this assignment

as a workaround, you can replace `TimeSpan` with a proxy value that can accept timespan-like string such as `KeyTime` to bypass this problem
