### ISSUE TITLE
ItemsRepeaterExtensions

### ISSUE THREAD

**Issue by kazo0** [unoplatform/uno.toolkit.ui#395]
#### Properties
| Property         	| Type               	| Description                                                                       	|
|------------------	|--------------------	|-----------------------------------------------------------------------------------	|
| SelectedItem     	| `object`           	| The currently selected item (for use when `SingleSelect="True"`)                  	|
| SelectedItems    	| `IList<object>`    	| The currently selected items (for use when `SingleSelect="False"`)                	|
| SelectedIndex    	| `IndexPath`        	| The index of the currently selected item (for use when `SingleSelect="True"`)     	|
| SelectedIndices  	| `IList<IndexPath>` 	| The indices of the currently selected items (for use when `SingleSelect="False"`) 	|
| SelectionMode     	| `None`, `Single`, `Multiple`             	| Determines whether the selection logic allows for multi- or single-select         	|

#### Events
| Event            	| Handler                                                                    	| Description                                       	|
|------------------	|----------------------------------------------------------------------------	|---------------------------------------------------	|
| SelectionChanged 	| `TypedEventHandler<ItemsRepeater, ItemsRepeaterSelectionChangedEventArgs>` 	| Occurs when the currently selected item(s) change 	|

#### Single Select
```xml
xmlns:utu="using:Uno.Toolkit.UI"
xmlns:muxc="using:Microsoft.UI.Xaml.Controls"

<muxc:ItemsRepeater ItemsSource="{Binding MyItems}"
                    utu:ItemsRepeaterExtensions.SelectionEnabled="True"
                    utu:ItemsRepeaterExtensions.SelectedItem="{Binding MySelectedItem, Mode=TwoWay}"
                    utu:ItemsRepeaterExtensions.SelectedIndex="{Binding MySelectedIndex, Mode=TwoWay}"
                    utu:ItemsRepeaterExtensions.SingleSelect="True"
                    utu:ItemsRepeaterExtensions.SelectionChanged="OnItemsRepeaterSelectionChange" />
```

#### Multi Select
```xml
xmlns:utu="using:Uno.Toolkit.UI"
xmlns:muxc="using:Microsoft.UI.Xaml.Controls"

<muxc:ItemsRepeater ItemsSource="{Binding MyItems}"
                    utu:ItemsRepeaterExtensions.SelectionEnabled="True"
                    utu:ItemsRepeaterExtensions.SelectedItems="{Binding MySelectedItems, Mode=TwoWay}"
                    utu:ItemsRepeaterExtensions.SelectedIndices="{Binding MySelectedIndices, Mode=TwoWay}"
                    utu:ItemsRepeaterExtensions.SingleSelect="False"
                    utu:ItemsRepeaterExtensions.SelectionChanged="OnItemsRepeaterSelectionChange" />
```

**Comment by kazo0** [comment]
Maybe `SelectionEnabled` can be removed and we would just have a enum similar to ListView with `SelectionMode.None`/`SelectionMode.Single`/`SelectionMode.Multiple`?

**Comment by kazo0** [comment]
Add a `SelectedItemStyle`? To be applied on any currently selected items

**Comment by Xiaoy312** [comment]
SelectionMode +1

Not sure about SelectedItemSTyle... I think it would be best to use a single "container" style for both selected and non-selected (distinguished by visual states). Ideally, it could be inherited from SelectorItem that has it built-in. If not, we could still ~~ab~~use `VisualStateManagerExtensions` to inject custom visual states.

**Comment by kazo0** [comment]
Looks like it may not be easy to have an event handler, such as one for SelectionChanged, as an attached property. We may need to drop SelectionChanged

**Comment by jeromelaban** [comment]
> @kazo0  Looks like it may not be easy to have an event handler, such as one for SelectionChanged, as an attached property. We may need to drop SelectionChanged

What would be the issue ?

**Comment by jeromelaban** [comment]
@dr1rrb for comments :)

**Comment by kazo0** [comment]
@jeromelaban would we be able to expose an event as as a static attached property?

**Comment by Xiaoy312** [comment]
The major problem is we can't really by contract have get-only attachable dependency property. The plural versions, SelectionItems and SelectionIndexes are get-only. Granted, we could re-route those to the respective callable methods.

And, we dont need to expose `SelectionChanged` event, as its purpose can be completely replaced with SelectionItem(s) or SelectionIndex(es).

**Comment by jeromelaban** [comment]
> @jeromelaban would we be able to expose an event as as a static attached property?

Not an event, but you should be able to have a property that takes a delegate. We should be testing this with WinUI though :)

**Comment by dr1rrb** [comment]
Investigating selection:

Agree that we should not have a `SelectionEnabled` and `SingleSelect` properties but instead have a `SelectionMode` of type `ItemsRepeaterSelectionMode` (like for [`ListView` and the `ListViewSelectionMode`](https://learn.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.listviewselectionmode?view=winrt-22621)

The `SelectionModel` which is already implemented in uno (for the `NavigationView` which also uses the `ItemsRepeater`) is still a preview feature for WinUI. It's actually just an helper class that ensure that the selected items are parts of the `Source` collection and raise events etc.  We should base our behavior om this class (and import implementation internally for UWP and WinUI).

**Comment by kazo0** [comment]
Concerning the following comments:

> What you described is essentially #395. There is a few problems that we need to solve if we want to add "generic" selection support for ItemsRepeater, which current spec doesnt cover or align with:
> 
> 1. "algorithm": user defined vs pre-packaged (ala SingleSelection=true/false or ListViewSelectionMode(none,single,multiple) or ChipSelectionMode(all previous+SingleOrNone). and, how to coordinate between them, or decide on one of them.
> 2. visual of selection: there are a few controls that supports selection visual built-in: SelectorItem, CheckBox, ToggleButton, and custom user control (eg: Chip), etc... And, those that do not: TextBlock, Grid. And, with the generic route, we need to figure out a way to link the state or the visual.
> 
> #451 can sort of serve as a foundation... which we can later expand on.

_Originally posted by @Xiaoy312 in https://github.com/unoplatform/uno.toolkit.ui/issues/452#issuecomment-1387329113_

### 1. SelectionMode

#### Proposed default modes
 - None
-  Single
- **SingleOrNone***
- Multiple

_*  Either implemented by default based on the [ChipGroup selection logic](https://github.com/unoplatform/uno.toolkit.ui/blob/main/doc/controls/ChipAndChipGroup.md#remarks) OR this can be part of a separate custom SelectionModel specifically for Chips (following the proposal for User-defined modes)_

#### User-defined modes
Perhaps we can expose some sort of `ISelectionModel` interface that the Extensions use as a means to drive the selection logic. So, by default, we have an internal `ItemsRepeaterSelectionModel : ISelectionModel` that handles the default Single/Multiple modes (I'm assuming by just wrapping the [WinUI SelectionModel](https://learn.microsoft.com/en-us/windows/winui/api/microsoft.ui.xaml.controls.selectionmodel?view=winui-2.8-prerelease) implementation) but you can also set the `ItemsRepeaterExtensions.SelectionModel` attached property to some custom implementation that the Extensions will use internally to drive selection instead.

### 1. Selection State of Items

I think as a first implementation we can at least handle the `SelectorItem` cases and adapt to other types later on. I feel `SelectorItem` is a good assumption for what the most common types of elements will be used in the lists.
