### ISSUE TITLE
Chip control name conflicts with the Chip namespace from Xamarin.iOS

### ISSUE THREAD

**Issue by takla21** [unoplatform/uno.toolkit.ui#399]
## Current behavior
I cannot compile on iOS because of this error.

![image](https://user-images.githubusercontent.com/17461593/201245620-2a72f5eb-d147-410c-b821-e1fd1ada291c.png)
```
MainPage.xaml.cs(11,17,11,21): error CS0118: 'Chip' is a namespace but is used like a type
```

## Expected behavior
I should be able to compile like on the other platforms

![image](https://user-images.githubusercontent.com/17461593/201245696-223b9a29-6e26-4a7b-9d63-1d981930b4da.png)

## How to reproduce it (as minimally and precisely as possible)

Download this sample [ChipSample.zip](https://github.com/unoplatform/uno.toolkit.ui/files/9985858/ChipSample.zip)
Try to Build/deploy on iOS

## Environment

Nuget Package: Uno.Toollkit.UI

Package Version(s): 2.4.0-dev.114

Affected platform(s):

- [x] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renders for Xamarin.Forms
- [ ] Windows
- [ ] Build tasks

Visual Studio:

- [x] 2022 (version: 17.3.5)
- [ ] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by Xiaoy312** [comment]
use the full name or a different alias: `using ChipControl = Uno.Toolkit.UI.Chip;`
