### ISSUE TITLE
Broken link to Improve Docs

### ISSUE THREAD

**Issue by nickrandolph** [unoplatform/uno.toolkit.ui#400]
The "Improve this Doc" link on some of the documentation pages leads to "Page not found"

eg https://platform.uno/docs/articles/external/uno.toolkit.ui/doc/material-migration.html

**Comment by Xiaoy312** [comment]
i feel like this stems from the difference in the default branch name,
where uno=master, and here=main

the same link from that page:
https://github.com/unoplatform/uno.toolkit.ui/blob/master/doc/material-migration.md/#L1
if you replace master by main, it will work:
https://github.com/unoplatform/uno.toolkit.ui/blob/main/doc/material-migration.md/#L1

**Comment by Xiaoy312** [comment]
need to adjust these for a more dynamic scenario:
https://github.com/unoplatform/uno/blob/4.6.19/doc/templates/uno/conceptual.html.primary.js#L12
https://github.com/unoplatform/uno/blob/4.6.19/doc/docfx.json#L48

CC: @jeromelaban

**Comment by Xiaoy312** [comment]
completed in unoplatform/uno#12036
