### ISSUE TITLE
ExtendedSplashScreen is not working properly

### ISSUE THREAD

**Issue by jeromelaban** [unoplatform/uno.toolkit.ui#427]
Here's my WIP prototype where I'm testing out the different parts that I need for the full application. I've stripped out most irrelevant parts, hopefully this can be used to repro. https://github.com/HakanL/UnoPrototype

_Originally posted by @HakanL in https://github.com/unoplatform/uno.toolkit.ui/discussions/426#discussioncomment-4355504_

**Comment by nickrandolph** [comment]
This has been fixed as we added support for Skia targets in 2.6 of toolkit
