### ISSUE TITLE
Selection support on Chip within ItemsRepeater

### ISSUE THREAD

**Issue by Xiaoy312** [unoplatform/uno.toolkit.ui#452]
## What would you like to be added:
Selection support on Chip within ItemsRepeater

## For which Platform:

- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renders for Xamarin.Forms
- [ ] Windows
- [ ] Build tasks

## Anything else we need to know?

**Comment by Xiaoy312** [comment]
```
<muxc:ItemsRepeater ItemsSource="{Binding Items}"
                    utu:ChipExtensions.ChipSelectionMode="Single">
    <muxc:ItemsRepeater.ItemTemplate>
        <DataTemplate>
            <utu:Chip Content="{Binding Name}" />
        </DataTemplate>
    </muxc:ItemsRepeater.ItemTemplate>
</muxc:ItemsRepeater>
```

`utu:ChipExtensions.ChipSelectionMode` functions exactly like `ChipGroup.SelectionMode`:
https://github.com/unoplatform/uno.toolkit.ui/blob/0f20755dd42b738fed80187d689d0e4ba8e2bfd7/doc/controls/ChipAndChipGroup.md?plain=1#L119-L124

**Comment by francoistanguay** [comment]
Can we make the selection algorithms independent from "Chips"? Simply ItemsRepeaterExtensions related to Selection?

**Comment by Xiaoy312** [comment]
What you described is essentially #395. There is a few problems that we need to solve if we want to add "generic" selection support for ItemsRepeater, which current spec doesnt cover or align with:
1. "algorithm": user defined vs pre-packaged (ala SingleSelection=true/false or ListViewSelectionMode(none,single,multiple) or ChipSelectionMode(all previous+SingleOrNone). and, how to coordinate between them, or decide on one of them.
2. visual of selection: there are a few controls that supports selection visual built-in: SelectorItem, CheckBox, ToggleButton, and custom user control (eg: Chip), etc... And, those that do not: TextBlock, Grid. And, with the generic route, we need to figure out a way to link the state or the visual.

#451 can sort of serve as a foundation... which we can later expand on.
