### ISSUE TITLE
BUG: [AutoLayout] Right Padding not taken into account in some scenarios

### ISSUE THREAD

**Issue by agneszitte-nventive** [unoplatform/uno.toolkit.ui#459]
## Current behavior

[AutoLayout] Right Padding not taken into account in some scenarios
![image](https://user-images.githubusercontent.com/16295702/214910153-faca4d47-7ee1-4d35-9ee9-25397fd5fcea.png)

## Expected behavior

[AutoLayout] Right Padding should be taken into account in all scenarios Figma support

## How to reproduce it (as minimally and precisely as possible)

A snippet of code is directly available in the playground here: https://playground.platform.uno/#0ba77d4e

```
<StackPanel Spacing="20">
    <utu:AutoLayout Spacing="8" Padding="40,0" Orientation="Horizontal">
        <PersonPicture Width="40" Height="40" />
        <utu:AutoLayout utu:AutoLayout.PrimaryAlignment="Stretch">
            <TextBlock Text="James Bondi" />
            <TextBlock Text="@jamesBondi" />
        </utu:AutoLayout>
        <Button Background="Blue" utu:AutoLayout.PrimaryAlignment="Auto" />
    </utu:AutoLayout>

    <utu:AutoLayout Spacing="8" Padding="40,0" Orientation="Horizontal">
        <PersonPicture Width="40" Height="40" />
        <utu:AutoLayout utu:AutoLayout.PrimaryAlignment="Stretch">
            <TextBlock Text="James Bondi" />
            <TextBlock Text="@jamesBondi" />
        </utu:AutoLayout>
        <Button Background="Blue" utu:AutoLayout.PrimaryAlignment="Stretch" />
    </utu:AutoLayout>

<!-- WORKAROUND -->
    <utu:AutoLayout Padding="40,0">
        <utu:AutoLayout Spacing="8" Orientation="Horizontal">
            <PersonPicture Width="40" Height="40" />
            <utu:AutoLayout utu:AutoLayout.PrimaryAlignment="Stretch">
                <TextBlock Text="James Bondi" />
                <TextBlock Text="@jamesBondi" />
            </utu:AutoLayout>
            <Button Background="Blue" utu:AutoLayout.PrimaryAlignment="Stretch" />
        </utu:AutoLayout>
    </utu:AutoLayout>
</StackPanel>
```

## Environment

Nuget Package: Uno.Toolkit.UI

Package Version(s): 2.5.0-dev.15

Affected platform(s):

- [X] All platforms

Visual Studio:

- [X] Microsoft Visual Studio Professional 2022 (64-bit) - Preview Version 17.5.0 Preview 2.0

## Anything else we need to know?

Related to this issue for Uno.Chefs: https://github.com/unoplatform/uno.chefs/issues/246

**Comment by Robert-Louis** [comment]
will fixed by this pr 
https://github.com/unoplatform/Uno.Figma/pull/1276
