### ISSUE TITLE
Adding Spacing into an Autolayout with only independent layout items prevents AL to show 

### ISSUE THREAD

**Issue by iury-kc** [unoplatform/uno.toolkit.ui#464]
### Current behavior

Seams that adding a Spacing property prevents the Autolayout to be rendered correctly if all its children have IsIndependentLayout set as True.

To reproduce the behavior:
Access: https://playground.platform.uno/#421b14a8
![image](https://user-images.githubusercontent.com/100223422/215839454-7a5d77d5-5656-41ce-b5d2-13d6b90396a4.png)

It works only if you:

1 - Add for instance a  <Button Content="Test" utu:Autolayout.CounterAlignment="Center"/> inside the main AutoLayout
2 - Remove Spacing attribute from main AutoLayout
![image](https://user-images.githubusercontent.com/100223422/215840056-eb52d3b5-0678-4292-adbd-ae9b5a0b05be.png)

BTW, canary, at 2023/01/31:
 https://playgroundcanary.z19.web.core.windows.net/#421b14a8
Won't render correctly in any case.

![image](https://user-images.githubusercontent.com/100223422/215840118-2998d7e8-5a2f-40a4-9a53-a4d159b4394c.png)

### Expected behavior

Intuitively, doesn't make sense having a Spacing, for sure, if all children are not dependent.
But, maybe would be better just ignoring the Spacing, instead not rendering the control.

### Works on UWP/WinUI

None

**Comment by iury-kc** [comment]
Not sure if it is related, but Material 2.5.0dev.18 coused a very similar behavior in Uno Plugin today.

**Comment by agneszitte-nventive** [comment]
@iury-kc this issue should be fixed with [Uno.Toolkit.UI/2.5.0-dev.20](https://www.nuget.org/packages/Uno.Toolkit.UI/2.5.0-dev.20).
If you can confirm please.

**Comment by iury-kc** [comment]
Fixed! Thanks!
