### ISSUE TITLE
[Specs] ShadowContainer

### ISSUE THREAD

**Issue by roubachof** [unoplatform/uno.toolkit.ui#470]
# Shadows for Uno specs

Name of the component: `ShadowContainer`
Type: `ContentControl`

## Properties

| Property  | Type                  | Description                                               |
| --------- | --------------------- | --------------------------------------------------------- |
| Shadows   | `ShadowCollection` | The list of shadows applied to the child of the container |
| Child     | `UIElement`           | The element that is casting the shadow                    |

### Shadow

Type: `DependencyObject`

| Property   | Type     | Description                                                         |
| ---------- | -------- | ------------------------------------------------------------------- |
| OffsetX     | `double`  | The shadow X offset                                                   |
| OffsetY     | `double`  | The shadow Y offset                                                   |
| Color      | `Color`  | The shadow Color                                                    |
| BlurRadius | `double` | The amount of blur applied to the Shadow [0..100]                   |
| Spread     | `double` | The amount the shadow should be inflated prior to applying the blur |
| Inner      | `bool`   | Shadows are drawn within the input content                          |

## Implementation

```
   +-Canvas---------------------------+
   |                                  |
   |  +-SKCanvasView---------------|  |
   |  |                            |  |
   |  |   +-Shadow-----+           |  |
   |  |   +-Shadow-----+           |  |
   |  |   +-Shadow-----+           |  |
   |  |                            |  |
   |  +-Child----------------------+  |
   |  |                            |  |
   |  |                            |  |
   |  |                            |  |
   |  +----------------------------+  |
   |                                  |
   +----------------------------------+
```

`Generic.xaml:`

```xml
<ResourceDictionary xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
                    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
                    xmlns:toolkit="using:Uno.Toolkit.UI">

    <Style TargetType="toolkit:DropShadowPanel">
        <Setter Property="Template">
            <Setter.Value>
                <ControlTemplate TargetType="toolkit:DropShadowPanel">
                    <Canvas>
                        <SKCanvasView x:Name="PART_Shadows" />
                        
                        <ContentPresenter ContentTemplate="{TemplateBinding Child}" />
                    </Canvas>
                </ControlTemplate>
            </Setter.Value>
        </Setter>
    </Style>

</ResourceDictionary>
```

Shadows drawing would occurs thanks to `SkiaSharp`:

1. We'll have the same result for each platform
2. We could benefit from hardware acceleration from OpenGL or even Vulkan (https://github.com/mono/SkiaSharp/issues/2104)

## Remarks

If the child is an image or text, we need to get the alpha mask or clipping path.
If the child is `Border` or `Control`, we can just apply the corner radius to the shadows.
In v1, I suggest we stick to simple child with corner radius.

### Declare shadows in dictionary

```xml
<ResourceDictionary xmlns="http://xamarin.com/schemas/2014/forms" xmlns:toolkit="using:Uno.Toolkit.UI">

    <ResourceDictionary.MergedDictionaries>
        <ResourceDictionary Source="Colors.xaml" />
    </ResourceDictionary.MergedDictionaries>

    <toolkit:ShadowCollection x:Key="NoShadow" />

    <toolkit:ShadowCollection x:Key="DarkNeumorphism">
       <toolkit:Shadow
            BlurRadius="3"
            Opacity="1"
            Offset="5,5"
            Color="#2b2b2b" />
        <toolkit:Shadow
            BlurRadius="3"
            Opacity="1"
            Offset="-5,-5"
            Color="#3a3a3a" />
    </toolkit:ShadowCollection>

</ResourceDictionary>
```

### Use shadows with resources

```xml
<ContentPage.Resources>
        <ResourceDictionary>
            <DataTemplate x:Key="VerticalDudeTemplate">
                <toolkit:DraggableViewCell x:Name="DraggableViewCell">
                    <toolkit:ShadowContainer
                        Shadows="{StaticResource DarkNeumorphism}">
                        <views:SillyListCell
                            Margin="16,13,16,13"
                            BackgroundColor="{StaticResource DarkerSurface}"
                            CornerRadius="10">
                            <views:SillyListCell.Triggers>
                                <DataTrigger
                                    Binding="{Binding Source={x:Reference DraggableViewCell}, Path=IsDragAndDropping}"
                                    TargetType="views:SillyListCell"
                                    Value="True">
                                    <Setter Property="BackgroundColor" Value="{StaticResource DarkSurface}" />
                                </DataTrigger>
                            </views:SillyListCell.Triggers>
                        </views:SillyListCell>
                    </toolkit:ShadowContainer>
                </toolkit:DraggableViewCell>
            </DataTemplate>

            ...
        </ResourceDictionary>
    </ContentPage.Resources>
```

![image](https://user-images.githubusercontent.com/596903/216974216-e76a06b8-6765-4405-ade8-2a62f07556fc.png)

### Use shadows directly

```xml
<Grid RowSpacing="10">
    <Grid.RowDefinitions>
        <RowDefinition x:Name="Description" Height="Auto" />
        <RowDefinition Height="100" />
        <RowDefinition Height="80" />
    </Grid.RowDefinitions>
    <Grid.ColumnDefinitions>
        <ColumnDefinition Width="*" />
        <ColumnDefinition Width="*" />
    </Grid.ColumnDefinitions>

    <Label Grid.Row="0"
           Grid.Column="0"
           Grid.ColumnSpan="2"
           Style="{StaticResource TextBodySecondary}"
           Margin="15,15"
           Text="Enter a world of colored shadows." />

        <toolkit:ShadowContainerx:Name="ButtonPlusColoredShadows"
                                  Grid.Row="1"
                                  Grid.Column="0">
        <toolkit:ShadowContainer.Shadows>
            <toolkit:ShadowCollection>
                <toolkit:Shadow BlurRadius="10"
                                Opacity="0.7"
                                Offset="0,10"
                                Color="Violet" />
            </toolkit:ShadowCollection>
        </toolkit:ShadowContainer.Shadows>
        <ImageButton Width="60"
                     Height="60"
                     Padding="20"
                     HorizontalAlignment="Center"
                     VerticalAlignment="Center"
                     BackgroundColor="Violet"
                     Clicked="ImageButtonOnClicked"
                     CornerRadius="30"
                     Source="{StaticResource IconPlusWhite}" />
    </toolkit:ShadowContainer>

    <toolkit:ShadowContainer Grid.Row="1"
                              Grid.Column="1"
                              Margin="0,10,0,0">
        <toolkit:ShadowContainer.Shadows>
            <toolkit:ShadowCollection>
                <toolkit:Shadow BlurRadius="10"
                                Opacity="0.5"
                                Offset="8,8"
                                Color="Yellow" />
                <toolkit:Shadow BlurRadius="10"
                                Opacity="0.5"
                                Offset="-8,-6"
                                Color="Violet" />
            </toolkit:ShadowCollection>
        </toolkit:ShadowContainer.Shadows>
        <Image Width="120"
               Margin="-20,0,0,0"
               HorizontalAlignment="Center"
               VerticalAlignment="Center"
               Source="{images:ImageResource nyan_cat.png}" />
    </sho:ShadowContainer>
```

![image](https://user-images.githubusercontent.com/596903/216973635-32cd6fc6-fcf7-4156-b80b-678bf3114321.png)

## Questions

* I don't know if a `SKCanvasView` exist for UNO?
* Do we have a xplat implementation of `GetAlphaMask` or a `GetClippingPath` for v2?

**Comment by NVLudwig** [comment]
Is it ok that these two share the same TYPE value? (NonDEV asking)
`<!DOCTYPE html>

BlurRadius | double | The amount of blur applied to the Shadow [0..100]
-- | -- | --
Spread | double | The amount the shadow should be inflated prior to applying the blur

`

**Comment by NVLudwig** [comment]
**Questions** (that may include scope creep)
Does offset include both X and Y values? (should)
Does Colour include transparency? (should)

Is there a way to get global light source set for multiple elements? (Nice to have)
A child can have multiple shadows right (should)?
![image](https://user-images.githubusercontent.com/29584087/217000506-1f9d650e-5f60-43ca-a363-a8931df1e7db.png)

**Comment by roubachof** [comment]
@NVLudwig yes to all questions except for light source.
Here we are only creating shadows. 
The shadows could be the result of a light source.
We could create a neumorphism component using the shadows component.

**Comment by jeromelaban** [comment]
Regarding a Skia-based backend, we'd likely need to have some sort of `ShadowPresenter` to allow the Skia canvas switching (`SKXamlCanvas` vs. the `SKSwapChainPanel`, where `SKSwapChainPanel` is not available on all targets), or even use native shadow primitives where it could make sense.

**Comment by roubachof** [comment]
# Support of colored shadows in native platforms

## Android

| Element      | Type       | Multiple           | GPU                | Implementation                     | Since |
| ------------ | ---------- | ------------------ | ------------------ | ---------------------------------- | ----- |
| Rectangle    | Canvas     | :white_check_mark: | :x:                | setMaskFilter()                    |       |
| CornerRadius | Canvas     | :white_check_mark: | :x:                | setMaskFilter()<br>drawRoundRect() | API21 |
| Inner shadow | :question: |                    |                    |                                    |       |
| Shape        | Canvas     | :white_check_mark: | :x:                | setMaskFilter()<br>drawPath()      |       |
| Text         | Canvas     | :white_check_mark: | :x:                | extractAlpha()<br>setMaskFilter()  |       |
| Text         | Native     | :x:                | :white_check_mark: | setShadowLayer()                   |       |
| Image        | Canvas     | :white_check_mark: | :x:                | extractAlpha()<br>setMaskFilter()  |       |


MAUI implementation:
* https://github.com/dotnet/maui/blob/83c3ac902ea496e409026c830ccd930c4021f8ab/src/Core/src/Platform/Android/WrapperView.cs

Hardware acceleration is possible:
* [through openGL](https://developer.android.com/develop/ui/views/graphics/opengl/about-opengl) 
* [RenderEffect starting Android 12](https://developer.android.com/reference/android/graphics/RenderEffect)
* [AGSL starting Android 13](https://developer.android.com/develop/ui/views/graphics/agsl).


## iOS

| Element      | Type       | Multiple           | GPU                | Implementation                                                             |
| ------------ | ---------- | ------------------ | ------------------ | -------------------------------------------------------------------------- |
| Rectangle    | CALayer    | :white_check_mark: | :white_check_mark: | CALayer.shadowXXX                                                          |
| CornerRadius | CALayer    | :white_check_mark: | :white_check_mark: | CALayer.shadowPath                                                         |
| Inner shadow | :question: |                    |                    |                                                                            |
| Shape        | CALayer    | :white_check_mark: | :white_check_mark: | CALayer.shadowPath                                                         |
| Text         | CALayer    | :question:         | :white_check_mark: | label.layer.shadowXXX<br>maybe multiple shadows would work with sublayers? |
| Image        | CALayer    | :white_check_mark: | :white_check_mark: | should work like label (uncertain)                                         |
|              |            |                    |                    |                                                                            |


MAUI implementation:
* https://github.com/dotnet/maui/blob/83c3ac902ea496e409026c830ccd930c4021f8ab/src/Core/src/Platform/iOS/WrapperView.cs

For good rendering perf, you need to set the shadowPath property on the CALayer, or else you will have a context switch between onscreen and offscreen rendering.
source: http://www.lukeparham.com/blog/2018/3/6/friends-dont-let-friends-render-offscreen

Inner shadow references: 
* https://stackoverflow.com/questions/4431292/inner-shadow-effect-on-uiview-layer
* https://stackoverflow.com/questions/69617588/creating-inner-shadows-in-uiview-to-replicate-neumorphic-style


## WinUI

| Element      | Type            | Multiple           | GPU | Implementation                  |
| ------------ | --------------- | ------------------ | --- | ------------------------------- |
| Rectangle    | Composition API | :white_check_mark: | :x: | SpriteVisual+CreateDropShadow() |
| CornerRadius | Composition API | :white_check_mark: | :x: | SpriteVisual+CreateDropShadow() |
| Inner shadow | :question:      |                    |     |                                 |
| Shape        | Composition API | :white_check_mark: | :x: | GetAlphaMask()                  |
| Text         | Composition API | :white_check_mark: | :x: | GetAlphaMask()                  |
| Image        | Composition API | :white_check_mark: | :x: | GetAlphaMask()                  |


MAUI implementation:
* https://github.com/dotnet/maui/blob/83c3ac902ea496e409026c830ccd930c4021f8ab/src/Core/src/Platform/Windows/WrapperView.cs

Other implementations:
* https://github.com/CommunityToolkit/WindowsCommunityToolkit/blob/77b009ddf591b78dfc5bad0088c99ce35406170b/Microsoft.Toolkit.Uwp.UI.Controls.Core/DropShadowPanel/DropShadowPanel.xaml
* https://github.com/roubachof/Sharpnado.Shadows/blob/master/Shadows/Shadows.UWP/UWPShadowsController.cs
* https://nicksnettravels.builttoroam.com/dropshadow/


## SkiaSharp

| Element      | Type       | Multiple           | GPU         | Implementation                        |
| ------------ | ---------- | ------------------ | ----------- | ------------------------------------- |
| Rectangle    | SKCanvas   | :white_check_mark: | :test_tube: | CreateDropShadow()                    |
| CornerRadius | SKCanvas   | :white_check_mark: | :test_tube: | CreateDropShadow()<br>DrawRoundRect() |
| Inner shadow | SKCanvas   | :white_check_mark: | :test_tube: | CreateDropShadow()                    |
| Shape        | SKCanvas   | :white_check_mark: | :test_tube: | convert path to skia path             |
| Text         | :question: |                    |             |                                       |
| Image        | :question: |                    |             |                                       |
|              |            |                    |             |                                       |


* https://github.com/roubachof/Sharpnado.Shadows/blob/master/Shadows/Shadows.Tizen/TizenShadowsRenderer.cs
* https://github.com/felipebaltazar/Xamarin.Forms.NeoControls/blob/master/Xamarin.Forms.NeoControls/NeoRoundedView.cs

From jerome :
> Regarding a Skia-based backend, we'd likely need to have some sort of ShadowPresenter to allow the Skia canvas switching (SKXamlCanvas vs. the SKSwapChainPanel, where SKSwapChainPanel is not available on all targets)

**Comment by NVLudwig** [comment]
@francoistanguay 2 cents: 
If implement _ShadowItem_ would it conflict with _SwipeItem_, could an item have both properties? 
e.g.: If I want an item in a list like a Card to swipe AND have a shadow would that be possible?

**Comment by kazo0** [comment]
We can have attached properties for the shadows, sort of like there is with `<Grid />` and `Grid.Row`/`Grid.Column`. So the element itself will be responsible for informing its parent (the `DropShadowsPanel`) of how it should be presented in the UI

```xml
<utu:DropShadowsPanel>
    <Image Width="120"
           Margin="-20,0,0,0"
           HorizontalAlignment="Center"
           VerticalAlignment="Center"
           Source="{images:ImageResource nyan_cat.png}">
        <utu:DropShadowsPanel.Shadows>
            <utu:Shadow BlurRadius="10"
                        Opacity="0.5"
                        Offset="8,8"
                        Color="Yellow" />
            <utu:Shadow BlurRadius="10"
                        Opacity="0.5"
                        Offset="-8,-6"
                        Color="Violet" />
        </utu:DropShadowsPanel.Shadows>
    </Image>
</utu:DropShadowsPanel>
```
or 

```xml
<utu:DropShadowsPanel>
    <Image Width="120"
            Margin="-20,0,0,0"
            HorizontalAlignment="Center"
            VerticalAlignment="Center"
            Source="{images:ImageResource nyan_cat.png}"
            utu:DropShadowsPanel.Shadows="{StaticResource DarkNeumorphism}" />
</utu:DropShadowsPanel>
```

And perhaps we can allow for inividual Shadow component properties as attached properties as well and infer a default SingleShadow with those property values. Something like:

```xml
<utu:DropShadowsPanel>
    <Image Width="120"
            Margin="-20,0,0,0"
            HorizontalAlignment="Center"
            VerticalAlignment="Center"
            Source="{images:ImageResource nyan_cat.png}"
            utu:DropShadowsPanel.BlurRadius="10"
            utu:DropShadowPanel.Offset="-10, 0"
            utu:DropShadowPanel.Color="Violet" />
</utu:DropShadowsPanel>
```

could result in a `SingleShadow` being added to the `DropShadowPanel` with the properties attached to the child element


And so would we need to define a separate `DropShadowPanel` for each control that we want to display a shadow? So if we had a more complex layout and we want to be able to display a shadow for multiple controls within that layout, would it be smart enough to handle something like:

```xml
<utu:DropShadowsPanel Grid.Row="1"
                        Grid.Column="1"
                        Margin="0,10,0,0">
    <Grid>
        <Grid.RowDefinitions>
            <RowDefinition Height="Auto" />
            <RowDefinition Height="*" />
            <RowDefinition Height="Auto" />
        </Grid.RowDefinitions>

        <Button Content="TopArea with Shadow">
            <utu:DropShadowsPanel.Shadows>
                <utu:Shadow BlurRadius="10"
                            Opacity="0.5"
                            Offset="8,8"
                            Color="Yellow" />
            </utu:DropShadowsPanel.Shadows>
        </Button>
        <Button Grid.Row="1"
                VerticalAlignment="Center"
                Content="MiddleArea" />
        <Button Grid.Row="2"
                Content="BottomArea">
            <utu:DropShadowsPanel.Shadows>
                <utu:Shadow BlurRadius="10"
                            Opacity="0.5"
                            Offset="8,8"
                            Color="Pink" />
            </utu:DropShadowsPanel.Shadows>
        </Button>
    </Grid>
</utu:DropShadowsPanel>
```

**Comment by kazo0** [comment]
As for naming, `ShadowPanel` maybe?

So then the child attached properties could be `ShadowPanel.BlurRadius`


Or perhaps `ShadowSurface` to depict that this would be the layer that the control's shadow is projected onto

**Comment by Xiaoy312** [comment]
Would this means that, toolkit will have an additional package dependency for non-skia targets?

**Comment by agneszitte** [comment]
Re-Open for backport PR

**Comment by agneszitte** [comment]
Related Epic issue: https://github.com/unoplatform/uno/issues/6183

**Comment by agneszitte** [comment]
Closing the issue as related PRs are now backported
