### ISSUE TITLE
[ItemsRepeater] Add pagination support

### ISSUE THREAD

**Issue by agneszitte** [unoplatform/uno.toolkit.ui#521]
## What would you like to be added: 
Pagination support for ItemsRepeater

From @dr1rrb :
Need to create a simple behavior that listens to the `EffectiveViewportChanged` event and triggers the `ISupportIncrementalLoading.LoadMoreItemsAsync` (https://learn.microsoft.com/en-us/uwp/api/windows.ui.xaml.data.isupportincrementalloading.loadmoreitemsasync?view=winrt-22621) on the `ItemsRepeater.ItemsSource `

## For which Platform:

- [X] All Platforms

## Anything else we need to know?
Right now these are the only extensions available for ItemsRepeater:
https://github.com/unoplatform/uno.toolkit.ui/blob/3accbd01e29c493385b0eb4403a1a3d035a6a384/doc/helpers/itemsrepeater-extensions.md

**Comment by pictos** [comment]
is the ItemRepeater virtualized, like ListView?

**Comment by dr1rrb** [comment]
> is the ItemRepeater virtualized, like ListView?

UI virtualized yes (rendering in the UI only items that are visible). But not data virtualized (loading items from the server only when needed) ... It's the subject of this issue :)

**Comment by pictos** [comment]
Yeah, I was wondering around the UI part, thanks for the answer
