### ISSUE TITLE
[Splashscreen][Resizetizer?] Default Android 12+ splashscreen looks odd

### ISSUE THREAD

**Issue by kazo0** [unoplatform/uno.toolkit.ui#529]
Create a Blank or Default Uno app from the templates and run the Android app on an API 31+ device/emulator:

![image](https://user-images.githubusercontent.com/4793020/228581708-89c09f7a-9d45-4dc9-b1d9-99f3f5684cb4.png)

Sample:
[UnoApp12.zip](https://github.com/unoplatform/uno.toolkit.ui/files/11102346/UnoApp12.zip)

**Comment by kazo0** [comment]
cc: @nickrandolph + @pictos

**Comment by pictos** [comment]
@kazo0 looking into your sample, the `style.xml` has the wrong files... Changing that everything looks pretty.

![image](https://user-images.githubusercontent.com/20712372/228705830-cdf08383-b740-4134-9297-801f7deb54f9.png)

**Comment by kazo0** [comment]
I never touched the style.xml file though, these were just apps I made using the Default template from the wizard

**Comment by pictos** [comment]
[UnoApp12_Updated.zip](https://github.com/unoplatform/uno.toolkit.ui/files/11107133/UnoApp12_Updated.zip)
