### ISSUE TITLE
[Splashscreen][Android] Fails to deploy/build after first successful run on device/emulator below API 31

### ISSUE THREAD

**Issue by kazo0** [unoplatform/uno.toolkit.ui#530]
1. Create a Blank of Default Uno app from the templates
2. Launch application onto a device/emulator at API level 30 or below
3. Attempt to launch the application from Visual Studio again (no matter that API level)
4. Observe: 
> APT2062: failed linking references 
resource drawable/splash_screen (aka com.companyname.UnoApp12:drawable/splash_screen) not found"

Performing a clean or rebuild avoids the problem

**Comment by kazo0** [comment]
cc: @nickrandolph + @pictos

**Comment by nickrandolph** [comment]
This has already been reported on both uno and resizetizer repositories, but a third time can't hurt :-) 
[#resize](https://github.com/unoplatform/uno.resizetizer/issues/106)

**Comment by Youssef1313** [comment]
Should be fixed now.
