### ISSUE TITLE
[Splashscreen][Android] Default system splashscreen on Android devices at API 30 or below is stretched and zoomed in

### ISSUE THREAD

**Issue by kazo0** [unoplatform/uno.toolkit.ui#531]
Create a Blank app from the Uno template (not Default)
Launch Android on a device/emulator at API level 30 or below
Observe:

## Android API 28:
<img width="635" alt="image" src="https://user-images.githubusercontent.com/4793020/228602653-1b2e9a5e-fed2-4fcc-94dc-1a63d56ceb2a.png">

## Android API 33:
<img width="687" alt="image" src="https://user-images.githubusercontent.com/4793020/228603918-be603a46-f0db-46ca-9504-30cdfe21d6b3.png">

**Comment by nickrandolph** [comment]
Fixed in uno.templates
