### ISSUE TITLE
[Sample App] NavigationView is almost unusable in the sample app in this repository

### ISSUE THREAD

**Issue by nickrandolph** [unoplatform/uno.toolkit.ui#544]
## Current behavior

On WinUI and UWP
![image](https://user-images.githubusercontent.com/1614057/232055442-038127ca-b1c8-4b3d-b2d1-69c34c8082c8.png)

## Expected behavior

The default style for the NavigationView should be usable and look good (assuming Material theme?)

## How to reproduce it (as minimally and precisely as possible)

Run the WinUI Sample app from this repository

## Environment

Nuget Package:

Package Version(s):

Affected platform(s):

- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renders for Xamarin.Forms
- [x] Windows
- [ ] Build tasks

Visual Studio:

- [ ] 2017 (version: )
- [ ] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by Marc-Antoine-Soucy** [comment]
well, it's not unusable anymore. The only issue we have left is that it often gets in compact mode instead of closing on a few platforms, but it's not a major issue, I think? I think we can probably close this.

**Comment by Marc-Antoine-Soucy** [comment]
hm, I can try to make it close completely on winUI
