### ISSUE TITLE
[SampleApp] NavigationBar isn't showing back button in sample app 

### ISSUE THREAD

**Issue by nickrandolph** [unoplatform/uno.toolkit.ui#545]
## Current behavior

In the NavigationBar pages in the Sample app, the Back button isn't showing when running the WinUI target

![image](https://user-images.githubusercontent.com/1614057/232056389-8a2403a1-c722-42f9-b6c7-61d2c5b9d485.png)

## Expected behavior

Back button should work

## How to reproduce it (as minimally and precisely as possible)

Run the WinUI target for the sample app in this repository
Go to NavigationBar
Click on Show Sample button
Click Navigation to Second Page button
No back button visible but it is there if you click on where the back button should be

## Environment

Nuget Package:

Package Version(s):

Affected platform(s):

- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renders for Xamarin.Forms
- [ ] Windows
- [ ] Build tasks

Visual Studio:

- [ ] 2017 (version: )
- [ ] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by jeromelaban** [comment]
@kazo0 yes, it's definitely possible to bundle assets now, in the same way bundling fonts is supported.

**Comment by kazo0** [comment]
We should bundle a scaled PNG asset (or can we bundle an SVG and have resizetizer do its magic?? @nickrandolph / @pictos )

**Comment by nickrandolph** [comment]
For the library we should package scaled assets to avoid a dependency on Resizetizer

**Comment by silviuo** [comment]
Currently working on #321 which should solve this as well
