### ISSUE TITLE
ExtendedSplashScreen crashes if no ProgressRing

### ISSUE THREAD

**Issue by dr1rrb** [unoplatform/uno.toolkit.ui#555]
## Current behavior
If there is no `ProgressRing` in the `LoadingContentTemplate`, the extended splash screen remains active even if page is loaded. The prevent any interaction with the page below.

## Expected behavior
We can put whatever we want in the template.

## How to reproduce it (as minimally and precisely as possible)
In the Uno.chefs project, in `App.xaml` replace the style of the `ExtendedSpalshScreen` by:
```xml
			<Style TargetType="utu:ExtendedSplashScreen"
				   BasedOn="{StaticResource DefaultExtendedSplashScreen}">
				<Setter Property="LoadingContentTemplate">
					<Setter.Value>
						<DataTemplate>
                            <!--<ProgressRing Height="32"
                                          HorizontalAlignment="Center"
                                          VerticalAlignment="Bottom"
                                          Margin="0, 0, 0, 200"
                                          IsActive="True" />-->
							<TextBlock Text="Loading ..." />
						</DataTemplate>
					</Setter.Value>
				</Setter>
			</Style>
```
Run the app and observe that nothing can be clicked (the splash screen remains active)

Nuget Package:

Package Version(s):

Affected platform(s):

- [ ] WebAssembly
- [ ] Android
- [ ] iOS
- [ ] macOS (AppKit)
- [ ] Mac Catalyst
- [x] Skia
  - [x] WPF
  - [ ] GTK (Linux)
  - [ ] Linux Framebuffer
  - [ ] Tizen
- [x] Windows

## Anything else we need to know?
I didn't validate, but this might also be an error in the Uno.Extensions.Navigation @nickrandolph

**Comment by nickrandolph** [comment]
This should be fixed in latest dev builds as we've set the splash and loading content to IsHitTestVisible = false
