### ISSUE TITLE
[ExtendedSplashScreen] splash image not loaded when WinUI set to unpackaged

### ISSUE THREAD

**Issue by nickrandolph** [unoplatform/uno.toolkit.ui#563]
## Current behavior

Set WinUI to unpackaged
No splash screen image set when WinUI set to unpackaged

## Expected behavior

Splash screen should be shown

## How to reproduce it (as minimally and precisely as possible)

Nuget Package:

Package Version(s):

Affected platform(s):

- [ ] WebAssembly
- [ ] Android
- [ ] iOS
- [ ] macOS (AppKit)
- [ ] Mac Catalyst
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Linux Framebuffer
  - [ ] Tizen
- [ ] Windows

IDE:

- [ ] Visual Studio 2022
- [ ] Visual Studio 2019
- [ ] Visual Studio Code
- [ ] Visual Studio for Mac
- [ ] Rider Windows
- [ ] Rider macOS

Relevant plugins:

**Comment by agneszitte** [comment]
@nickrandolph I am closing this older issue in favor of https://github.com/unoplatform/uno.toolkit.ui/issues/1185
