### ISSUE TITLE
`ExtendedSplashScreen` is not documented

### ISSUE THREAD

**Issue by Youssef1313** [unoplatform/uno.toolkit.ui#574]
## Concern?

- [ ] Usage in industry
- [x] Clarification of capabilities
- [x] Getting started with Uno
- [x] Developing with Uno
- [ ] Contributing to the Uno project
- [ ] Publishing your application
- [ ] Support
- [ ] Other (please specify):

## For which Platform:

- [x] iOS
- [x] Android
- [x] WebAssembly
- [x] Windows

**Comment by nickrandolph** [comment]
Docs for this will be on Toolkit. I think there's a basic doc that covers some aspects but a full walkthrough would be nice

**Comment by agneszitte** [comment]
@kazo0 / @nickrandolph / @pictos if you have additional info or comments on what is missing for the doc at the moment for the `ExtendedSplashScreen` please add them in the comment of this issue so anyone can pick up to adjust it

**Comment by HakanL** [comment]
It would be great to document how to do this in all platforms, for me it's not working in Skia (no logo), but I haven't spent much time troubleshooting it.

**Comment by kazo0** [comment]
@nickrandolph / @HakanL  I see [this doc](https://github.com/unoplatform/uno.toolkit.ui/blob/main/doc/controls/ExtendedSplashScreen.md) but it's not included in the TOC so I will add it. But I think we'll need to expand it a bit with more explanation and examples eventually

**Comment by agneszitte** [comment]
@kazo0 I will let you check with @lukeblevins if he can give a hand to expand a bit with more explanation and examples.
As I also ping him in this other issue https://github.com/unoplatform/uno/issues/13338#issuecomment-1852278149

**Comment by lukeblevins** [comment]
> I see this doc [ExtendedSplashScreen.md](https://github.com/unoplatform/uno.toolkit.ui/blob/main/doc/controls/ExtendedSplashScreen.md) 
> I think we'll need to expand it a bit with more explanation and examples eventually

Working on this item (see context above from @kazo0 in https://github.com/unoplatform/uno.toolkit.ui/issues/574#issuecomment-1852175498)
