### ISSUE TITLE
[iOS][Android] AppBarButton breaks NavigationBar if Icon specified

### ISSUE THREAD

**Issue by mikeirvingweb** [unoplatform/uno.toolkit.ui#586]
## Current behavior

Navigation Bar does not render (at all) on Mobile, if an Icon is used

error in Output - `System.InvalidOperationException: The Dependency Property [UriSource] is owned by [Microsoft.UI.Xaml.Controls.BitmapIcon] and cannot be used on [Microsoft.UI.Xaml.Controls.SymbolIcon]`

## Expected behavior

Navigation Bar renders, and the button has the desired icon, like on Windows

## How to reproduce it (as minimally and precisely as possible)

`<utu:NavigationBar Content="Macclesfield Hedgehogs">`
`	<utu:NavigationBar.PrimaryCommands>`
`		<AppBarButton Label="Refresh" Icon="Refresh" />`
`	</utu:NavigationBar.PrimaryCommands>`
`</utu:NavigationBar>`

Affected platform(s):

- [X] Android
- [X] iOS

**Comment by kazo0** [comment]
Thanks for the report @mikeirvingweb!

Unfortunately only BitmapIcons can be supported by the NavigationBar for Mobile targets at this time as the underlying native components do no support Font/Path/Symbol Icons. See [here](https://platform.uno/docs/articles/external/uno.toolkit.ui/doc/controls/NavigationBar.html#how-can-i-use-a-path-for-the-appbarbutton-icon)

Some investigation still needs to be done to see if this would be possible in the future but for right now we only have support for `BitmapIcon`.

**Comment by mikeirvingweb** [comment]
Yeah. A pain though. It's nice to be able to use Symbol Icons elsewhere, but painful to have to make bitmaps, or use just text, here.

Yes, I feel it should not break the navbar altogether, and if the error made the cause obvious it would save devs a lot of time

**Comment by mikeirvingweb** [comment]
By 'not breaking' the nav bar, it should just default to the `Label`, if one has been provided.
