### ISSUE TITLE
[Gallery][Wasm/iOS/Android]FAB- when changing theme FAB buttons are not getting properly refresh.

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/uno.toolkit.ui#591]
### Current behavior

https://github.com/unoplatform/uno/assets/74563602/d2b6dbc6-574c-413a-a7ba-b329e5ba2479

![FAB issue theme](https://github.com/unoplatform/uno/assets/74563602/0740d902-b043-48f1-abff-67c6d60f81c7)

### Expected behavior

![FAB  correct theme](https://github.com/unoplatform/uno/assets/74563602/4d5972f8-b9c1-42e8-9259-426b183ddae9)

### How to reproduce it (as minimally and precisely as possible)

1. Open Uno Gallery APP .
2. Click/tap Burger Menu on the left top right.
3. Click/tap "Floating Action Button" from the "Component" list.
4. Click on the theme toggle button.
5. Notice that theme change to dark theme.
6. Observe that FAB buttons are not getting refreshed with changing theme.

### Works on UWP/WinUI

None

### Affected platforms

WebAssembly, Android, iOS

**Comment by lesterbotello** [comment]
Hi @sakshi173, this seems to be fixed now after https://github.com/unoplatform/Uno.Themes/issues/1007 was completed. Might want to re-test this, and probably close it

**Comment by sakshi173** [comment]
This issue is resolved, closing it.
