### ISSUE TITLE
Use SafeArea in the Samples App

### ISSUE THREAD

**Issue by kazo0** [unoplatform/uno.toolkit.ui#593]
We should be using the [SafeArea](https://platform.uno/docs/articles/external/uno.toolkit.ui/doc/controls/SafeArea.html?tabs=none) in the Shell, rather than doing things like this: https://github.com/unoplatform/uno.toolkit.ui/blob/80ebae884de8d6ba6b27c2d8a7dce296904374b0/samples/Uno.Toolkit.Samples/Uno.Toolkit.Samples.Shared/Shell.xaml.cs#L85-L101

We should also be making sure the app content, including the runtime test runner page, all stay within the bounds of the safe area

**Comment by carlh98** [comment]
@kazo0 when this PR is merged https://github.com/unoplatform/uno.toolkit.ui/pull/616
We'll be able to close this issue
