### ISSUE TITLE
[WinUI][AutoLayout] Right padding becomes negative under certain conditions

### ISSUE THREAD

**Issue by Marc-Antoine-Soucy** [unoplatform/uno.toolkit.ui#624]
## Current behavior
The right padding should not become negative

![image](https://github.com/unoplatform/uno.toolkit.ui/assets/90481654/bd90fc9f-e332-4610-a417-cbe7c14459b1)

## Expected behavior

It should stay positive, like in on WASM.
![image](https://github.com/unoplatform/uno.toolkit.ui/assets/90481654/6cb59398-6f95-405b-972f-4d85885a6466)

## How to reproduce it (as minimally and precisely as possible)
```
<utu:AutoLayout
        Padding="32"
        Background="{ThemeResource ApplicationPageBackgroundThemeBrush}"
        Spacing="16">
        <utu:AutoLayout Orientation="Horizontal">
            <utu:AutoLayout utu:AutoLayout.PrimaryAlignment="Stretch">
                <TextBlock utu:AutoLayout.CounterAlignment="End" Text="987654321" />
            </utu:AutoLayout>
        </utu:AutoLayout>
        <TextBlock
            HorizontalAlignment="Right"
            Text="Content outside of this pattern will also have it's content cut-off 987654321"
            TextAlignment="End" />
 </utu:AutoLayout>
```
The second textbox and the spacing on the first layout is just there to demonstrate that the padding becomes negative for the all the content below the first autolayout. The rest seems to be necessary, I tried to simplify it as much as I could.

[BasicApp.zip](https://github.com/unoplatform/uno.toolkit.ui/files/11883308/BasicApp.zip)

Nuget Package:
```
		<PackageReference Include="Uno.Resizetizer" Version="1.2.0-dev.4" />
		<PackageReference Include="Uno.Toolkit.WinUI" Version="3.1.0-dev.18" />
		<PackageReference Include="Uno.WinUI" Version="4.10.0-dev.146" />
		<PackageReference Include="Microsoft.WindowsAppSDK" Version="1.2.230313.1" />
		<PackageReference Include="Microsoft.Windows.SDK.BuildTools" Version="10.0.22621.755" />
		<PackageReference Include="CommunityToolkit.Mvvm" Version="8.1.0" />
		<PackageReference Include="Microsoft.Extensions.Logging.Console" Version="7.0.0" />
		<PackageReference Include="Uno.Core.Extensions.Logging.Singleton" Version="4.0.1" />
		<PackageReference Include="Uno.UI.Adapter.Microsoft.Extensions.Logging" Version="4.10.0-dev.146" />
```
Package Version(s):

Affected platform(s):

- [ ] WebAssembly
- [ ] Android
- [ ] iOS
- [ ] macOS (AppKit)
- [ ] Mac Catalyst
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Linux Framebuffer
  - [ ] Tizen
- [X] Windows

IDE:

- [X] Visual Studio 2022
- [ ] Visual Studio 2019
- [ ] Visual Studio Code
- [ ] Visual Studio for Mac
- [ ] Rider Windows
- [ ] Rider macOS
17.6.0
Relevant plugins:

**Comment by Marc-Antoine-Soucy** [comment]
It looks like it can also happen on WASM but under different conditions.

**Comment by agneszitte** [comment]
> It looks like it can also happen on WASM but under different conditions.

@Marc-Antoine-Soucy please add a proper snippet of code if you can so @Robert-Louis will be able to replicate the issue on Wasm also. Thanks in advance

**Comment by Marc-Antoine-Soucy** [comment]
Adding HorizontalAlignment="Left" to the AutoLayout with the padding is what makes the bug reproduceable on WASM.
![image](https://github.com/unoplatform/uno.toolkit.ui/assets/90481654/648ea599-2600-46e9-8057-6e11c797b4dc)
```    
    <utu:AutoLayout
        Padding="32"
        HorizontalAlignment="Left"
        Background="{ThemeResource ApplicationPageBackgroundThemeBrush}"
        Spacing="16">
        <utu:AutoLayout Orientation="Horizontal">
            <utu:AutoLayout utu:AutoLayout.PrimaryAlignment="Stretch">
                <TextBlock utu:AutoLayout.CounterAlignment="End" Text="987654321" />
            </utu:AutoLayout>
        </utu:AutoLayout>
        <TextBlock
            HorizontalAlignment="Right"
            Text="Content outside of this pattern will also have it's content cut-off 987654321"
            TextAlignment="End" />
    </utu:AutoLayout>
```

**Comment by Marc-Antoine-Soucy** [comment]
There is another way that you can get this bug, and this makes the bug reproduceable on all platforms I tested WinUI, WASM, and Mobile, and skia. 

The important part of the code is this: 
```
<utu:AutoLayout
            x:Name="ContentLayout"
            Padding="16"
            utu:AutoLayout.PrimaryAlignment="Stretch"
            Spacing="18">
            <Grid utu:AutoLayout.PrimaryAlignment="Stretch">
                <utu:AutoLayout
                    utu:AutoLayout.CounterAlignment="Stretch"
                    utu:AutoLayout.PrimaryAlignment="Stretch"
                    Spacing="18">

                    <Grid utu:AutoLayout.CounterAlignment="Stretch" utu:AutoLayout.PrimaryAlignment="Stretch">

                        <uer:FeedView NoneTemplate="{StaticResource RecipeEmptyTemplate}" Source="{Binding SavedRecipes}">
                            <DataTemplate>
                                <muxc:ItemsRepeater ItemTemplate="{StaticResource RecipeTemplate}" ItemsSource="{Binding Data}">
                                    <muxc:ItemsRepeater.Layout>
                                        <muxc:UniformGridLayout
                                            ItemsStretch="Fill"
                                            MaximumRowsOrColumns="2"
                                            MinColumnSpacing="10"
                                            MinItemWidth="100"
                                            MinRowSpacing="10" />
                                    </muxc:ItemsRepeater.Layout>
                                </muxc:ItemsRepeater>
                            </DataTemplate>
                        </uer:FeedView>
                    </Grid>
                </utu:AutoLayout>
            </Grid>
        </utu:AutoLayout>
```

On this branch I simplified the code : https://github.com/unoplatform/uno.chefs/tree/dev/maso/autolayoutbug

I did not make a sample app because I found I was spending a bit too much time on this and it might be fixed when the rest is fixed. But, if you think it would be important for me to do the sample app, you can ask me.

Steps to reproduce bug: 
Open the app. 
Press on skip at the top or next three times
Write anything in the username and the password section and press on sign in
Press on Saved on the bottom or side bar 
![image](https://github.com/unoplatform/uno.toolkit.ui/assets/90481654/d4192762-36e1-497c-bb3d-4a891608c2cb)

See that the items on the right get cutoff
![image](https://github.com/unoplatform/uno.toolkit.ui/assets/90481654/05b36f2a-f93c-4d40-8f9a-290101f8a035)
when they should all be identical.

**Comment by Robert-Louis** [comment]
it's interesting without the HorizontalAlignment="Left" only the item repeater is cut 

with the HorizontalAlignment="Left" the issue happen for every control but only  on winUI and Skia

![image](https://github.com/unoplatform/uno.toolkit.ui/assets/16021239/ee1eb1ce-6d90-428d-957a-4541955ff6a0)

```
<utu:AutoLayout
            x:Name="ContentLayout"
            Padding="50,0"
            utu:AutoLayout.PrimaryAlignment="Stretch"
            Spacing="0">

        <Button utu:AutoLayout.PrimaryAlignment="Stretch" CornerRadius="25" Background="Blue" Height="100"/>

        <Rectangle utu:AutoLayout.PrimaryAlignment="Stretch" Fill="Pink" Height="50"/>
        <utu:AutoLayout Orientation="Horizontal">
            <utu:AutoLayout utu:AutoLayout.PrimaryAlignment="Stretch">
                <TextBlock utu:AutoLayout.CounterAlignment="End" Text="987654321" />
            </utu:AutoLayout>
        </utu:AutoLayout>
        <TextBlock HorizontalAlignment="Right"
                       Text="Content outside of this pattern will also have it's content cut-off 987654321"
                       TextAlignment="End"
                       TextWrapping="Wrap"/>

        <muxc:ItemsRepeater ItemTemplate="{StaticResource RecipeTemplate}" ItemsSource="{Binding ints}" utu:AutoLayout.PrimaryAlignment="Stretch">
            <muxc:ItemsRepeater.Layout>
                <muxc:UniformGridLayout
                                    ItemsStretch="Fill"
                                    MaximumRowsOrColumns="2"
                                    MinColumnSpacing="10"
                                    MinItemWidth="130"
                                    MinRowSpacing="10" />
            </muxc:ItemsRepeater.Layout>
        </muxc:ItemsRepeater>
    </utu:AutoLayout>

```

**Comment by Robert-Louis** [comment]
@Marc-Antoine-Soucy it's fixed in latest Toolkit

**Comment by agneszitte** [comment]
@Robert-Louis I synced with @Marc-Antoine-Soucy and seems like it is fixed for some cases but some not with the latest packages.
I will let him double-check and come back to you with more info as needed.

**Comment by Marc-Antoine-Soucy** [comment]
This bug seems fixed to me

**Comment by agneszitte** [comment]
Closing this issue as fixed with latest packages (<PackageReference Include="Uno.Toolkit.WinUI" Version="4.0.0-dev.39" />)

Another issue was opened for another right margin regression: https://github.com/unoplatform/uno.toolkit.ui/issues/653
