### ISSUE TITLE
Toolkit Samples Planning

### ISSUE THREAD

**Issue by kazo0** [unoplatform/uno.toolkit.ui#63]
This issue is used to track progress and plans for the samples within the Toolking Samples App

## NavigationBar

Skia/WASM:
![image](https://user-images.githubusercontent.com/4793020/135286038-64ef1c02-f71d-48b7-acfe-adbb4a0dd8ab.png)

iOS:
![iosnavbar2](https://user-images.githubusercontent.com/4793020/135288308-09116862-490b-4b6d-8e10-05310233d7dc.gif)

## Material TabBar
![MicrosoftTeams-image (14)](https://user-images.githubusercontent.com/4793020/135288551-5a54ed27-81f1-4d28-8a2d-c68dafa526f9.png)

## Cupertino TabBar
![MicrosoftTeams-image (13)](https://user-images.githubusercontent.com/4793020/135288599-6d46b815-acee-4fab-9b90-f8d06332f0f7.png)

**Comment by agneszitte-nventive** [comment]
@kazo0 I think we can close this issue now no ?
