### ISSUE TITLE
Autolayout expanding horizontally beyond the page limit

### ISSUE THREAD

**Issue by eriklimakc** [unoplatform/uno.toolkit.ui#633]
## Current behavior

Autolayout expands beyond page limit and content gets cropped. May be related to Padding + Spacing.

![image](https://github.com/unoplatform/uno.toolkit.ui/assets/114886335/5172b22c-8ad2-4086-bbf7-1d714082724c)

## Expected behavior
Page limits to be respected by Autolayout.

![image](https://github.com/unoplatform/uno.toolkit.ui/assets/114886335/d7f09bd5-cbe8-416f-bcc8-3bac1837d511)

## How to reproduce it (as minimally and precisely as possible)

Nuget Package:

Package Version(s):

Uno.Toolkit.WinUI.Material 3.1.0-dev.23

Affected platform(s):

- [X] WebAssembly
- [X] Android
- [ ] iOS
- [ ] macOS (AppKit)
- [ ] Mac Catalyst
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Linux Framebuffer
  - [ ] Tizen
- [ ] Windows

IDE:

- [ ] Visual Studio 2022
- [ ] Visual Studio 2019
- [ ] Visual Studio Code
- [ ] Visual Studio for Mac
- [ ] Rider Windows
- [ ] Rider macOS

Relevant plugins:

**Comment by Robert-Louis** [comment]
same issue as https://github.com/unoplatform/uno.toolkit.ui/issues/624

**Comment by agneszitte** [comment]
> same issue as #624

closing as it is a duplicate issue
