### ISSUE TITLE
[NavigationBar] Multiple NavigationBar causes crash on WinUI

### ISSUE THREAD

**Issue by Marc-Antoine-Soucy** [unoplatform/uno.toolkit.ui#658]
## Current behavior
If you have NavigationBar on two different tabs (ie nested on a single page) when you switch tabs you'll see an exception on winUI

![image](https://github.com/unoplatform/uno.toolkit.ui/assets/1614057/5615f3b9-fc7d-484a-a855-9d98b8f965cc)

## Expected behavior

Navigation between two tabs should work

## How to reproduce it (as minimally and precisely as possible)
Navigate to one of the two tabs, notice if both home and saved have a NavigationBar, the app crashes when you try to navigate from one to the next.

[unoExtensionBasicApp.zip](https://github.com/unoplatform/uno.extensions/files/12070303/unoExtensionBasicApp.zip)

(Uncomment the NavigationBar on Home before running, and then switch tabs)

## Environment

Nuget Package:
```
 <PackageVersion Include="Uno.Extensions.Configuration" Version="3.0.0-dev.1960" />
    <PackageVersion Include="Uno.Extensions.Hosting" Version="2.4.2" />
    <PackageVersion Include="Uno.Extensions.Hosting.WinUI" Version="3.0.0-dev.1960" />
    <PackageVersion Include="Uno.Extensions.Http" Version="3.0.0-dev.1960" />
    <PackageVersion Include="Uno.Extensions.Http.Refit" Version="3.0.0-dev.1960" />
    <PackageVersion Include="Uno.Extensions.Localization" Version="2.4.2" />
    <PackageVersion Include="Uno.Extensions.Localization.WinUI" Version="3.0.0-dev.1960" />
    <PackageVersion Include="Uno.Extensions.Logging.OSLog" Version="1.6.0-dev.2" />
    <PackageVersion Include="Uno.Extensions.Logging.WebAssembly.Console" Version="1.6.0-dev.2" />
    <PackageVersion Include="Uno.Extensions.Logging.WinUI" Version="3.0.0-dev.1960" />
    <PackageVersion Include="Uno.Extensions.Navigation" Version="2.4.2" />
    <PackageVersion Include="Uno.Extensions.Navigation.WinUI" Version="3.0.0-dev.1960" />
    <PackageVersion Include="Uno.Extensions.Navigation.Toolkit.WinUI" Version="3.0.0-dev.1960" />
    <PackageVersion Include="Uno.Extensions.Reactive" Version="2.4.2" />
    <PackageVersion Include="Uno.Extensions.Reactive.WinUI" Version="3.0.0-dev.1960" />
    <PackageVersion Include="Uno.Extensions.Serialization" Version="2.4.2" />
    <PackageVersion Include="Uno.Extensions.Serialization.Http" Version="3.0.0-dev.1960" />
    <PackageVersion Include="Uno.Extensions.Serialization.Refit" Version="3.0.0-dev.1960" />
    <PackageVersion Include="Uno.Material.WinUI" Version="3.0.0-dev.262" />
```
Package Version(s):

Affected platform(s):

- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renders for Xamarin.Forms
- [X] Windows
- [ ] Build tasks

Visual Studio:

- [ ] 2017 (version: )
- [X] 2022 (version: 17.6)
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by kazo0** [comment]
fixed by https://github.com/unoplatform/uno.toolkit.ui/pull/860

just need to update packages
