### ISSUE TITLE
[AutoLayout] Collapsed elements in autolayout still takes space

### ISSUE THREAD

**Issue by Marc-Antoine-Soucy** [unoplatform/uno.toolkit.ui#660]
## Current behavior
You can see this in this gif were you switch visibility between two grids. (AutoLayout to the left, StackPanel to the right)
![collapsedbutnot](https://github.com/unoplatform/uno.toolkit.ui/assets/90481654/b82279a5-cfc2-4bdf-bd91-8ac8f5eed297)

In this gif, where the blue grid is being collapsed, you can see that it still takes space in the AutoLayout while it doesnt in the StackPanel.

![collapsedbutnot2](https://github.com/unoplatform/uno.toolkit.ui/assets/90481654/8d25a834-8664-4ad1-a4f8-8735be62a4d7)

## Expected behavior
I would expect collapsed element in an AutoLayout to stop taking space, just like they do in a StackPanel.

## How to reproduce it (as minimally and precisely as possible)

```
	<Grid Background="{ThemeResource ApplicationPageBackgroundThemeBrush}">
		<utu:AutoLayout>
			<Grid Height="200"
				  Width="200"
				  Background="Blue"
				  Visibility="{Binding Element1Visibility}">
				<TextBlock Text="Grid in Autolayout"
						   VerticalAlignment="Center" />
			</Grid>
			<Grid Height="200"
				  Width="200"
				  Background="Red"
				  Visibility="{Binding Element2Visibility}">
				<TextBlock Text="Grid in Autolayout"
						   VerticalAlignment="Center" />
			</Grid>
		</utu:AutoLayout>
		<StackPanel Margin="200,0,0,0">
			<Grid Height="200"
				  Width="200"
				  Background="Blue"
				  Visibility="{Binding Element1Visibility}">
				<TextBlock Text="Grid in Stackpanel" 
						   VerticalAlignment="Center"/>

			</Grid>
			<Grid Height="200"
				  Width="200"
				  Background="Red"
				  Visibility="{Binding Element2Visibility}">
				<TextBlock Text="Grid in Stackpanel"
						   VerticalAlignment="Center" />
			</Grid>
		</StackPanel>


		<Button Click="Button_Click" 
				Content="Change visibility"/>
	</Grid>
```
[BasicApp.zip](https://github.com/unoplatform/uno.toolkit.ui/files/12094631/BasicApp.zip)
To test, just click on the button and notice the blue grid always takes space in the AutoLayout and does not in the StackPanel.

Nuget Package:
```
		<PackageReference Include="Uno.Toolkit.WinUI" Version="4.0.0-dev.52" />
		<PackageReference Include="Uno.WinUI" Version="5.0.0-dev.1441" />
```
Package Version(s):

Affected platform(s):
The bug is present on all platform tested

- [X] WebAssembly
- [X] Android
- [X] iOS
- [ ] macOS (AppKit)
- [ ] Mac Catalyst
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Linux Framebuffer
  - [ ] Tizen
- [X] Windows

IDE:

- [X] Visual Studio 2022 17.60
- [ ] Visual Studio 2019
- [ ] Visual Studio Code
- [ ] Visual Studio for Mac
- [ ] Rider Windows
- [ ] Rider macOS

Relevant plugins:

**Comment by Robert-Louis** [comment]
@agneszitte  @Marc-Antoine-Soucy  it should be fixed by this pr https://github.com/unoplatform/uno.toolkit.ui/pull/663
