### ISSUE TITLE
[WinUI/ShadowContainer] ThemeResources used inside ShadowContainer are not changing when switching themes

### ISSUE THREAD

**Issue by agneszitte** [unoplatform/uno.toolkit.ui#707]
## Current behavior

ThemeResources used inside ShadowContainer are not changing when switching themes in the sample app. If the theme switching is done using `RequestedTheme` instead in App.xaml the issue is not present.

## Expected behavior

ThemeResources used inside ShadowContainer should be properly updated when switching themes

## How to reproduce it (as minimally and precisely as possible)

- Current behavior when switching to Dark Theme with the snippet below 
![image](https://github.com/unoplatform/uno.toolkit.ui/assets/16295702/c06a5c99-6d8f-4725-b47f-f4f593d7daaf)

- Expected behavior when switching to Dark Theme with the snippet below 
(can be tested directly using RequestedTheme=Dark in App.xaml)
![image](https://github.com/unoplatform/uno.toolkit.ui/assets/16295702/2855dd98-ed21-4b58-bbba-520003d0f10f)

Snippet available on this branch: https://github.com/unoplatform/uno.toolkit.ui/tree/dev/agzi/ShadowContainerThemeSwitchingIssue

```
<!-- Test issue Theme Switching -->
							<Border>
								<Border.Resources>
									<ResourceDictionary>
										<ResourceDictionary.ThemeDictionaries>
											<!-- Shadow Styles ColorPaletteOverride -->
											<ResourceDictionary x:Key="Dark">
												<Color x:Key="OnSurfaceColor">#E6E1E5</Color>
												<Color x:Key="OnSurfaceVariantColor">#C9C5D0</Color>
												<Color x:Key="PrimaryColor">#C7BFFF</Color>

												<SolidColorBrush x:Key="OnSurfaceBrush"
																 Color="{StaticResource OnSurfaceColor}" />

												<SolidColorBrush x:Key="OnSurfaceVariantBrush"
																 Color="{StaticResource OnSurfaceVariantColor}" />

												<SolidColorBrush x:Key="PrimaryBrush"
																 Color="{StaticResource PrimaryColor}" />
												
												<!-- Shadow colors-->
												<Color x:Key="LightShadowColor">#3C3846</Color>
												<Color x:Key="ShadeShadowColor">#24222A</Color>
												
											</ResourceDictionary>
											<ResourceDictionary x:Key="Light">
												<Color x:Key="OnSurfaceColor">#1C1B1F</Color>
												<Color x:Key="OnSurfaceVariantColor">#8A8494</Color>
												<Color x:Key="PrimaryColor">#5946D2</Color>

												<SolidColorBrush x:Key="OnSurfaceBrush"
																 Color="{StaticResource OnSurfaceColor}" />

												<SolidColorBrush x:Key="OnSurfaceVariantBrush"
																 Color="{StaticResource OnSurfaceVariantColor}" />

												<SolidColorBrush x:Key="PrimaryBrush"
																 Color="{StaticResource PrimaryColor}" />

												<!-- Shadow colors-->
												<Color x:Key="LightShadowColor">#FFFFFF</Color>
												<Color x:Key="ShadeShadowColor">#AEAEC0</Color>
											</ResourceDictionary>
										</ResourceDictionary.ThemeDictionaries>

										<utu:ShadowCollection x:Key="NeumorphismBulgingTest">
											<utu:Shadow BlurRadius="10"
														IsInner="True"
														OffsetX="-5"
														OffsetY="-5"
														Opacity="1"
														Spread="0"
														Color="{ThemeResource LightShadowColor}" />
											<utu:Shadow BlurRadius="10"
														IsInner="True"
														OffsetX="4"
														OffsetY="4"
														Opacity="1"
														Spread="0"
														Color="{ThemeResource ShadeShadowColor}" />
										</utu:ShadowCollection>
									</ResourceDictionary>
								</Border.Resources>

								<utu:ShadowContainer Shadows="{StaticResource NeumorphismBulgingTest}">
									<Button Width="80"
											Height="80"
											Background="{ThemeResource OnSurfaceBrush}"
											BorderBrush="{ThemeResource OnSurfaceVariantBrush}"
											Content="Circular"
											CornerRadius="40"
											Foreground="{ThemeResource PrimaryBrush}" />
								</utu:ShadowContainer>
							</Border>
```

Nuget Package: Uno.Toolkit.UI 

Package Version(s): 4.0.0-dev.67

Affected platform(s):

- [X] Windows
- [?] Double-check properly the other platforms

IDE:

- [X] Visual Studio 2022
- [ ] Visual Studio 2019
- [ ] Visual Studio Code
- [ ] Visual Studio for Mac
- [ ] Rider Windows
- [ ] Rider macOS

**Comment by agneszitte** [comment]
FYI @Xiaoy312 please also test the case where ShadowCollection is changed in the visual states when switching themes while the app is running. (Previous related PR for more details: https://github.com/unoplatform/uno.toolkit.ui/issues/697)

**Comment by Xiaoy312** [comment]
this setup works everywhere:
```xml
<utu:ShadowContainer Shadows="{ThemeResource NeumorphismBulgingTest}" />
...
<ResourceDictionary>
	<ResourceDictionary.ThemeDictionaries>
		<ResourceDictionary x:Key="Dark">
			<Color x:Key="LightShadowColor">Pink</Color>
			<Color x:Key="ShadeShadowColor">SkyBlue</Color>

			<utu:ShadowCollection x:Key="NeumorphismBulgingTest">
				<utu:Shadow BlurRadius="10" IsInner="True" OffsetX="-5" OffsetY="-5" Opacity="1" Spread="0" Color="{StaticResource LightShadowColor}" />
				<utu:Shadow BlurRadius="10" IsInner="True" OffsetX="4" OffsetY="4" Opacity="1" Spread="0" Color="{StaticResource ShadeShadowColor}" />
			</utu:ShadowCollection>
		</ResourceDictionary>
		<ResourceDictionary x:Key="Light">
			<Color x:Key="LightShadowColor">Orange</Color>
			<Color x:Key="ShadeShadowColor">Green</Color>

			<utu:ShadowCollection x:Key="NeumorphismBulgingTest">
				<utu:Shadow BlurRadius="10" IsInner="True" OffsetX="-5" OffsetY="-5" Opacity="1" Spread="0" Color="{StaticResource LightShadowColor}" />
				<utu:Shadow BlurRadius="10" IsInner="True" OffsetX="4" OffsetY="4" Opacity="1" Spread="0" Color="{StaticResource ShadeShadowColor}" />
			</utu:ShadowCollection>
		</ResourceDictionary>
	</ResourceDictionary.ThemeDictionaries>
</ResourceDictionary>
```
the shadow-collection itself needs to be duplicated in theme-dict
you can even inline the color on the Shadow itself if we arent reusing them

**Comment by agneszitte** [comment]
@eriklimakc can you test please and keep @Xiaoy312 updated if it is fixing the issue properly, thanks in advance

**Comment by eriklimakc** [comment]
So Shadows colors are changing accordingly. But we have another problem. 

For example for TextBox styles in Gallery, the ShadowContainer with Shadows is preventing the TextBox background from changing according to the Theme, but when I removed the Shadows from the ShadowContainer the TextBox background changes accordingly:

### Without Shadows

![has no shadow](https://github.com/unoplatform/uno.toolkit.ui/assets/114886335/5cf77760-998d-481f-9b69-a6af411a0914)

### With Shadows

![has shadow to shadowcontainer](https://github.com/unoplatform/uno.toolkit.ui/assets/114886335/1211920d-8d1c-4f3a-b18a-1218a8e07265)

cc @Xiaoy312 @agneszitte

**Comment by Xiaoy312** [comment]
ok... so i found the cause of ShadowContainer not reacting to theme switch...
the background SC's child actually get cleared to Transparent, and is re-implemented as the "foundation" for the shadow imagebrush
the problem being that, it doesnt listen for further updates on its background like direct assignment, binding and theme changes...
\---
the challenge being that, we cant really just simply remove this mechanism, as the inner shadows would have to be applied on top of the background
one way of approaching this, is to listen for the bg changes and re-paint; but i ran into problem where i cant listen for the value change on certain setup like {ThemeResource}, because they are not binding. and even if we have Binding or TemplateBinding, it is still tricky to obtain new value, if we cleared the source binding by setting a transparent on where the binding would be...
\---
to be explored: duplicate the skxamlcanvas, one for outer shadow and one for inner shadow, sandwiching the actual child

**Comment by eriklimakc** [comment]
Not sure if it's the same issue, I think it's similar since it's all related to InnerShadows. To repro, checkout this branch [dev/erli/shadow-themeswitching-repro](https://github.com/unoplatform/Uno.Gallery/tree/dev/erli/shadow-themeswitching-repro) in Gallery.

InnerShadows "dissapearing":

1. TextBox/PasswordBox/ComboBox
2. FAB 
3. Strange behavior with Chips shadows
4. TabBarItem shadows not updating

![Recording 2023-08-18 145814](https://github.com/unoplatform/uno.toolkit.ui/assets/114886335/511c794e-9ff5-44eb-b4b9-4f74a6fbd976)

**Comment by Xiaoy312** [comment]
the textbox border problem on skia should go away with #737

**Comment by agneszitte** [comment]
Re-Open issue as changes reverted in https://github.com/unoplatform/uno.toolkit.ui/pull/751
@Xiaoy312 is revisiting the problem

**Comment by agneszitte** [comment]
Re-Open still work in progress
