### ISSUE TITLE
[ShadowContainer] Inner Shadows not properly fitted in Rectangle and Ellipse

### ISSUE THREAD

**Issue by eriklimakc** [unoplatform/uno.toolkit.ui#740]
## Current behavior
 Inner Shadows not properly fitted in Rectangle and Ellipse:
 
 
![image](https://github.com/unoplatform/uno.toolkit.ui/assets/114886335/8102a950-e02f-47d4-893a-514267980e97)

## Expected behavior
The shadows to be properly fitted inside the the element as it happens with Grid and Border:

![image](https://github.com/unoplatform/uno.toolkit.ui/assets/114886335/b3bf5efd-b598-4ff7-8b77-e3bbe841b8f4)

## How to reproduce it (as minimally and precisely as possible)

Grab the repro below and launch.

**Comment by agneszitte** [comment]
Re-Open for backports
