### ISSUE TITLE
[WASM] Text cut-off in some Material Bottom Tab Bar Items

### ISSUE THREAD

**Issue by kazo0** [unoplatform/uno.toolkit.ui#75]
## Current behavior

![MicrosoftTeams-image](https://user-images.githubusercontent.com/4793020/139107312-1729b13b-60b5-4b1f-8483-50e88ac6d602.png)

## Environment

Nuget Package:

Package Version(s):

Affected platform(s):

- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renders for Xamarin.Forms
- [ ] Windows
- [ ] Build tasks

Visual Studio:

- [ ] 2017 (version: )
- [ ] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by agneszitte-nventive** [comment]
Closing this issue as it's not visible anymore with latest for the text for WASM (Uno.UI [4.0.9] / Uno.Material [1.2.0]).
But another issue is now visible with latest for the icons for WASM, details here: https://github.com/unoplatform/uno.toolkit.ui/issues/178 

(cc @kazo0 / @jeromelaban)
