### ISSUE TITLE
[ControlExtensions] Add CustomResources Attached Property

### ISSUE THREAD

**Issue by kazo0** [unoplatform/uno.toolkit.ui#779]
We want to be able to have a DependencyProperty for static resources. Right now [Resources](https://learn.microsoft.com/en-us/uwp/api/windows.ui.xaml.frameworkelement.resources?view=winrt-22621) is not a DP so you can't use it in a Setter for a Style to say that a specific style should override/contain certain resources.

It would be useful to have an attached property that you can use in a Style.Setter to define a ResourceDictionary where you can put whatever you want. This would allow for a new Style to be defined with overrides to Lightweight Styling resources without re-defining the ControlTemplate

**Comment by Marc-Antoine-Soucy** [comment]
@agneszitte @kazo0  This should be closed, no? I'm fairly sure this is the same issue as this: https://github.com/unoplatform/uno.toolkit.ui/issues/870

**Comment by kazo0** [comment]
closed as dupe of https://github.com/unoplatform/uno.toolkit.ui/issues/870
