### ISSUE TITLE
[ShadowContainer] Cache issue on CornerRadius

### ISSUE THREAD

**Issue by rafael-rosa-knowcode** [unoplatform/uno.toolkit.ui#782]
## What would you like to be added:

When running the tests for the ShadowsContainer.
We use the a 
Border (Width="200", Height="200"),
![image](https://github.com/unoplatform/uno.toolkit.ui/assets/116665025/0427d877-4706-4039-8714-0401d1e1a55d)

Rectangle (Width="200", Height="200") and 
![image](https://github.com/unoplatform/uno.toolkit.ui/assets/116665025/3c932b8e-4818-4632-b733-12898c011bf0)

Border (Width="200", Height="200", CornerRadius="0,200,0,200"),
![image](https://github.com/unoplatform/uno.toolkit.ui/assets/116665025/6b202873-6b82-45da-9568-4149f4cdaed5)

When the test is performed with the corner radius parameters in the border. Shadows assumes the element's corner radius.
However, when we go back to the border element without the corner radius, it is being cut to the shape of the one with the corner radius.

This is causing the test that has the same parameters to fail during execution.

When using 9 and -9.
![image](https://github.com/unoplatform/uno.toolkit.ui/assets/116665025/18888acd-5e9f-4361-8401-d1845d2b5257)

When using 10 and -10
![image](https://github.com/unoplatform/uno.toolkit.ui/assets/116665025/41842095-8586-4a18-aca7-011dac935c73)

The situation only happens when we run the tests at once. Individually tests pass.

## Why is this needed:

It could be a problem when creating the test, but it could be a problem with the cornerRadius cache.

## For which Platform:

- [x] WebAssembly
- [ ] Android
- [ ] iOS
- [ ] macOS (AppKit)
- [ ] Mac Catalyst
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Linux Framebuffer
  - [ ] Tizen
- [ ] Windows

**Comment by agneszitte** [comment]
Re-Open for backports
