### ISSUE TITLE
[Docs][Lightweight Styling] Fix XAML/Screenshot sample

### ISSUE THREAD

**Issue by kazo0** [unoplatform/uno.toolkit.ui#783]
<img alt="image" src="https://github.com/unoplatform/uno.toolkit.ui/assets/4793020/6e132af5-8c41-426e-9c8e-74642a9037d5">

The XAML does not fully match with the screenshot of the chips, we should show the xaml for the Default chip as well and have an example of the Overridden chip without the pointer over state so we can see all lightweight styling resource overrides at work

**Comment by carlh98** [comment]
![image](https://github.com/unoplatform/uno.toolkit.ui/assets/7770915/251ef1ba-8bd9-4416-bb52-c29800ebd895)
![image](https://github.com/unoplatform/uno.toolkit.ui/assets/7770915/72bf87a0-319e-4bcd-826f-9b61f5a5d7da)
@kazo0

**Comment by kazo0** [comment]
@carlh98 

1. Let's split the xaml into three separate Chips, one Default, one Overridden like the Green one, and then a separate one that has the PointerOver resources overridden
2. Change the "Overriden" to "Overridden"
3. You can just provide the code block of the XAML here instead of a screenshot, that way I can copy paste it into the docs and the release blog post

**Comment by agneszitte** [comment]
Re-Open for backport PR
