### ISSUE TITLE
[ShadowContainer] CornerRadius performance issue

### ISSUE THREAD

**Issue by rafael-rosa-knowcode** [unoplatform/uno.toolkit.ui#789]
## What would you like to be added:

The PR [[ShadowContainer] Inner Shadows not properly fitted in Rectangle and Ellipse](https://github.com/unoplatform/uno.toolkit.ui/pull/757#top) add the CornerRadius handle for non uniform corner radius.

But we need to update the performance of the code, so we open this issue referring to the discussion in the original PR
https://github.com/unoplatform/uno.toolkit.ui/pull/757#discussion_r1310738482

So now we need to change the usage of linq to array.

## Why is this needed:

For better performance.

## For which Platform:

- [x] WebAssembly
- [ ] Android
- [ ] iOS
- [ ] macOS (AppKit)
- [ ] Mac Catalyst
- [x] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Linux Framebuffer
  - [ ] Tizen
- [ ] Windows

**Comment by agneszitte** [comment]
Re-Open for backports
