### ISSUE TITLE
[ShadowContainer][All Platforms] ShadowContainer not resizing properly

### ISSUE THREAD

**Issue by kazo0** [unoplatform/uno.toolkit.ui#798]
ShadowContainer is correctly stretching iwhen the content is changed to be larger but if the content is then shrunk, the ShadowContainer does not resize:

See Shadow Builder control inside of the Toolkit sample app:

![shadowcontainerstretch](https://github.com/unoplatform/uno.toolkit.ui/assets/4793020/bc0b52d2-2dad-4bb1-a1f8-bc8a2f04fd8a)

**Comment by agneszitte** [comment]
Re-Open for backports

**Comment by agneszitte** [comment]
Re-Open for backport
