### ISSUE TITLE
[Card] Update the control to have Primary / Secondary commands

### ISSUE THREAD

**Issue by agneszitte-nventive** [unoplatform/uno.toolkit.ui#84]
## Current behavior

For the Card control:
- The "Action" buttons are at the moment in the supporting template
- The "Icon" buttons are at the moment in the icons template

## Expected behavior

Update this above to have Primary / Secondary templates instead

Affected platform(s):

- [ ] All platforms

## Anything else we need to know?

Refactor to better suit Figma generation

**Comment by agneszitte-nventive** [comment]
@kazo0 / @Xiaoy312 I'm not sure about this one if it is still needed ?

**Comment by Xiaoy312** [comment]
Doesnt look like it. We can shelve/close this, and re-open in the future as needed.
