### ISSUE TITLE
[Android][Chips] Chips not correctly aligned when inside UniformGridLayout

### ISSUE THREAD

**Issue by eriklimakc** [unoplatform/uno.toolkit.ui#850]
## Current behavior
Linked to https://github.com/unoplatform/uno.chefs/pull/572#issuecomment-1719797697

When inside an ItemsRepeater with UniformGridLayout Chips aren't correctly aligned on Android as follows:

![android-itemsrepeater-uniformgridlayout-chips](https://github.com/unoplatform/uno.toolkit.ui/assets/114886335/fa72fb36-7145-4130-8ec1-2358a5312124)

## How to reproduce it (as minimally and precisely as possible)

[Chips-UniformGridLayout-Repro.zip](https://github.com/unoplatform/uno.toolkit.ui/files/12619751/Chips-UniformGridLayout-Repro.zip)

Affected platform(s):

- [ ] WebAssembly
- [X] Android
- [ ] iOS
- [ ] macOS (AppKit)
- [ ] Mac Catalyst
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Linux Framebuffer
  - [ ] Tizen
- [ ] Windows

**Comment by agneszitte** [comment]
UniformGridLayout is not the proper Panel to use here with ununiform items so closing this issue (+ we are not using chips anymore for these)
