### ISSUE TITLE
Uno.Toolkit.WinUI should not expose content files

### ISSUE THREAD

**Issue by jeromelaban** [unoplatform/uno.toolkit.ui#854]
## Current behavior

`contentFiles` are present following workarounds applied before https://github.com/unoplatform/uno/pull/13581. The workaround should be removed once Uno is updated.

This causes assets to be incorrectly included in the output of projects referencing uno.toolkit.winui, and `ExcludeAssets="contentFiles"` is required as a result.

**Comment by VincentH-Net** [comment]
When I add `ExcludeAssets="contentFiles"` to the `Uno.Toolkit.WinUI` package reference in my own NuGet `CSharpMarkup.WinUI.Uno.Toolkit`, the windows target build errors in the app that references `CSharpMarkup.WinUI.Uno.Toolkit` reduce from:
![image](https://github.com/unoplatform/uno.extensions/assets/1872271/8dfe81fe-39ee-4c39-892b-1dbea0d2ca6e)
to:
![image](https://github.com/unoplatform/uno.extensions/assets/1872271/6ee4af5e-e697-48c5-8dc7-593e99dd8efe)

Adding `ExcludeAssets="contentFiles"` to the `CSharpMarkup.WinUI.Uno.Toolkit` package reference and / or the `Uno.Toolkit.WinUI` package references in the app does not remove these remaining errors - any idea how to do that?

PS I am also using this workaround for the Windows target in both the app project and my own NuGet project:
`<WindowsAppSDKWinUI>true</WindowsAppSDKWinUI> <!-- Workaround for https://github.com/unoplatform/uno/discussions/13569 -->`

**Comment by VincentH-Net** [comment]
I lost patience and implemented a hack workaround:

For the Windows target I just copied and referenced the DLLs out of the offending Uno NuGets, instead of using the NuGets themselves. I had to leave out the `.PRI` files for the DLLs - they also reference the assets.

Note that `Uno.Extensions.Hosting.WinUI` has the same problem as `Uno.Toolkit.WinUI` (see error messages in above screenshots)

If anyone wants to use this workaround: [here is the diff](https://github.com/VincentH-Net/CSharpForMarkup/commit/af94fc59cb7412b2a9df8b7ee5b45013b7c3c0fc)

**Comment by VincentH-Net** [comment]
After resolving issues with the initial workaround above, here is a summary of the issue and final workaround.

The workaround is quite elaborate. Are there 4.x packages available where this has been fixed? Thanks!

# Issue:
When creating a NuGet that directly **or indirectly** references `Uno.Toolkit.WinUI` or  `Uno.Extensions.Hosting.WinUI` NuGets, build errors as in above screenshot occur for the Windows target in an app that references the created NuGet.

No combination of `ExcludeAssets` and/or `PrivateAssets` will resolve all of these errors.

# Workaround:
Instead of the `Uno.Toolkit.WinUI` or  `Uno.Extensions.Hosting.WinUI` NuGet reference, include the assemblies fron those NuGets plus references for all NuGets that they depend on, with `ExcludeAssets="build;analyzers;contentFiles" PrivateAssets="all"`

E.g.:
```xml
	<ItemGroup Condition="$(IsUno)==false">  <!--Workaround for https://github.com/unoplatform/uno.extensions/discussions/1921 : use this instead of PackageReference Include="Uno.Extensions.Navigation.WinUI" Version="2.5.11"--> 
		<Reference Include="Uno.Extensions.Navigation.UI.NoAssets">
			<HintPath>..\uno.extensions.navigation.winui-2.5.11-libnet6.0-windows10.0.18362\Uno.Extensions.Navigation.UI.dll</HintPath>
		</Reference>
		<Reference Include="Uno.Extensions.Hosting.WinUI.NoAssets">
			<HintPath>..\uno.extensions.hosting.winui-2.5.11-libnet6.0-windows10.0.18362\Uno.Extensions.Hosting.WinUI.dll</HintPath>
		</Reference>
		 <!--Dependencies for Uno.Extensions.Navigation.UI--> 
		<PackageReference Include="Uno.Extensions.Core.WinUI" Version="2.5.11" ExcludeAssets="build;analyzers;contentFiles" PrivateAssets="all" />
		<PackageReference Include="Uno.Extensions.Navigation" Version="2.5.11" ExcludeAssets="build;analyzers;contentFiles" PrivateAssets="all" />
		<PackageReference Include="Microsoft.Extensions.Localization.Abstractions" Version="6.0.4" ExcludeAssets="build;analyzers;contentFiles" PrivateAssets="all" />
		<PackageReference Include="Microsoft.Windows.SDK.BuildTools" Version="10.0.22621.756" ExcludeAssets="build;analyzers;contentFiles" PrivateAssets="all" />
		<PackageReference Include="Uno.Core" Version="4.0.1" ExcludeAssets="build;analyzers;contentFiles" PrivateAssets="all" />
		<PackageReference Include="Uno.WinUI" Version="4.9.20" ExcludeAssets="build;analyzers;contentFiles" PrivateAssets="all" />

		 <!--Dependencies for Uno.Extensions.Hosting.WinUI--> 
		<PackageReference Include="Uno.Extensions.Core" Version="2.5.11" ExcludeAssets="build;analyzers;contentFiles" PrivateAssets="all" />
		<PackageReference Include="Uno.Extensions.Hosting" Version="2.5.11" ExcludeAssets="build;analyzers;contentFiles" PrivateAssets="all" />
		<PackageReference Include="Uno.Extensions.Storage.WinUI" Version="2.5.11" ExcludeAssets="build;analyzers;contentFiles" PrivateAssets="all" />
		<PackageReference Include="Uno.Extensions.Storage" Version="2.5.11" ExcludeAssets="build;analyzers;contentFiles" PrivateAssets="all" />
		<PackageReference Include="Microsoft.Extensions.Hosting" Version="6.0.1" ExcludeAssets="build;analyzers;contentFiles" PrivateAssets="all" />
	</ItemGroup>
```

and

```xml
	<ItemGroup Condition="$(IsUno)==false">
		 <!--Workaround for https://github.com/unoplatform/uno.extensions/discussions/1921 : use this instead of PackageReference Include="Uno.Extensions.Reactive.WinUI" Version="2.5.11"--> 
		<Reference Include="Uno.Extensions.Reactive.UI.NoAssets">
			<HintPath>..\uno.extensions.reactive.winui.2.5.11-libnet6.0-windows10.0.18362\Uno.Extensions.Reactive.UI.dll</HintPath>
		</Reference>
		 <!--Dependencies for Uno.Extensions.Reactive.UI--> 
		<PackageReference Include="Uno.Extensions.Reactive" Version="2.5.11" ExcludeAssets="build;analyzers;contentFiles" PrivateAssets="all"  />
		<PackageReference Include="Microsoft.Bcl.AsyncInterfaces" Version="6.0.0" ExcludeAssets="build;analyzers;contentFiles" PrivateAssets="all"  />
		<PackageReference Include="Microsoft.Windows.SDK.BuildTools" Version="10.0.22621.756" ExcludeAssets="build;analyzers;contentFiles" PrivateAssets="all"  />
		<!--<PackageReference Include="Uno.Toolkit.WinUI" Version="3.0.4" ExcludeAssets="build;analyzers" /> replaced with next itemgroup - same workaround-->
		<PackageReference Include="Uno.WinUI" Version="4.9.20" ExcludeAssets="build;analyzers" />
	</ItemGroup>

	<ItemGroup Condition="$(IsUno)==false">
		<!--Workaround for https://github.com/unoplatform/uno.extensions/discussions/1921 : use this instead of PackageReference Include="Uno.Toolkit.WinUI" Version="4.2.22"-->
		<Reference Include="Uno.Toolkit.WinUI.NoAssets">
			<HintPath>..\uno.toolkit.winui-4.2.22-lib-net6.0-windows10.0.18362\Uno.Toolkit.WinUI.dll</HintPath>
		</Reference>
		<PackageReference Include="Uno.Toolkit" Version="4.2.22" ExcludeAssets="build;analyzers;contentFiles" PrivateAssets="all" />
		<PackageReference Include="Uno.Core.Extensions.Collections" Version="4.0.1" ExcludeAssets="build;analyzers;contentFiles" PrivateAssets="all" />
		<PackageReference Include="Uno.Core.Extensions.Logging" Version="4.0.1" ExcludeAssets="build;analyzers;contentFiles" PrivateAssets="all" />
		<PackageReference Include="Uno.Core.Extensions.Logging.Singleton" Version="4.0.1" ExcludeAssets="build;analyzers;contentFiles" PrivateAssets="all" />
		<PackageReference Include="Uno.WinUI" Version="4.7.37" ExcludeAssets="build;analyzers;contentFiles" PrivateAssets="all" />
	</ItemGroup>
```

**Comment by jeromelaban** [comment]
Fixed in latest toolkit build!
