### ISSUE TITLE
Move the custom controls and related styles created in Uno.Themes to Uno.UI.Toolkit

### ISSUE THREAD

**Issue by agneszitte** [unoplatform/uno.toolkit.ui#86]
### Description

Move the custom controls and related styles created in Uno.Themes to Uno.Toolkit.UI

#### Affected controls:
- [x] Card **[Needs to be moved in Toolkit]**
(https://github.com/unoplatform/uno.ui.toolkit/pull/142 / https://github.com/unoplatform/Uno.Themes/pull/683)
- [x] Chip **[Needs to be moved in Toolkit]**
(https://github.com/unoplatform/uno.ui.toolkit/pull/114 / https://github.com/unoplatform/Uno.Themes/pull/676 )
- [x] StandardBottomSheet **[Needs to be removed from Uno.Themes]** 
(https://github.com/unoplatform/Uno.Themes/pull/678)
- [x] BottomNavigationBar / BottomNavigationBarItem **[Need to be removed from Uno.Themes]**
(https://github.com/unoplatform/Uno.Themes/pull/681)
- [x] Divider **[Needs to be moved in Toolkit]**
 (https://github.com/unoplatform/uno.ui.toolkit/pull/105 / https://github.com/unoplatform/Uno.Themes/pull/655)
- [x] ExpandingBottomSheet **[Needs to be removed from Uno.Themes]**
(https://github.com/unoplatform/Uno.Themes/pull/678)
- [x] ModalStandardBottomSheet **[Needs to be removed from Uno.Themes]**
(https://github.com/unoplatform/Uno.Themes/pull/678)
- [x] Ripple **[Stays in Uno.Themes, no changes]**
- [x] SnackBar **[Needs to be removed from Uno.Themes]**
(https://github.com/unoplatform/Uno.Themes/pull/679)

### More information
- All the custom controls + related styles, and test samples (Generic / Material / Cupertino) should be in **Uno.Toolkit.UI**.
- All the WinUI-based controls  (+Ripple as helper) + related styles and test samples (Material / Cupertino) should be in **Uno.Themes**.
- All the showcase samples for WinUI controls, Uno.UI.Toolkit controls and related styles (Material / Cupertino / Fluent / Native) should be in **Uno.Gallery**.

**Comment by ConroyG** [comment]
It looks like BottomNavigationBar was only removed from Uno.Themes and never added to Toolkit.Ui
Was this a mistake? or is the control gone?
