### ISSUE TITLE
Incorrect render of DocFx alert

### ISSUE THREAD

**Issue by weitzhandler** [unoplatform/uno.toolkit.ui#897]
## On which page?
https://platform.uno/docs/articles/external/uno.toolkit.ui/doc/getting-started.html

https://github.com/unoplatform/uno.toolkit.ui/blob/31028b21593d885d79873371c3d3271c72fa6482/doc/getting-started.md?plain=1#L10

## What's wrong?

![image](https://github.com/unoplatform/uno.toolkit.ui/assets/2716316/14affa14-2d8e-4d36-868c-f942e900457c)

## Any feedback?

It could be happening because of the colon after `[!NOTE]`.

@kazo0

**Comment by weitzhandler** [comment]
@kazo0

**Comment by Xiaoy312** [comment]
for alert tag, you need to follow it immediately with a newline:
```md
> [!NOTE]
> Information the user should notice even if skimming.
```
see: https://dotnet.github.io/docfx/docs/markdown.html?tabs=linux%2Cdotnet#alerts
