### ISSUE TITLE
Autolayout Counter Alignment + Padding leads to wrong result

### ISSUE THREAD

**Issue by iurycarlos** [unoplatform/uno.toolkit.ui#919]
## Current behavior

In a very simple design, the counter alignment center is not followed correctly if the container has padding.

## Expected behavior

Should work correctly.

## How to reproduce it (as minimally and precisely as possible)

The code for reproduce the error is at the snippet:

https://playgroundcanary.z19.web.core.windows.net/#392f406e

Nuget Package:

Package Version(s):

Affected platform(s):

- [ ] WebAssembly
- [ ] Android
- [ ] iOS
- [ ] macOS (AppKit)
- [ ] Mac Catalyst
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Linux Framebuffer
  - [ ] Tizen
- [ ] Windows

IDE:

- [ ] Visual Studio 2022
- [ ] Visual Studio 2019
- [ ] Visual Studio Code
- [ ] Visual Studio for Mac
- [ ] Rider Windows
- [ ] Rider macOS

Relevant plugins:

**Comment by kazo0** [comment]
cc @Robert-Louis

**Comment by iurycarlos** [comment]
@Robert-Louis I think you fixed this one, right?

**Comment by iurycarlos** [comment]
Canary working:



![Image](https://github.com/unoplatform/uno.toolkit.ui/assets/6876973/a0494472-ddff-42b7-b3bf-0ce9155cf91c)
