### ISSUE TITLE
Remove need for ResponsiveHelper init calls 

### ISSUE THREAD

**Issue by kazo0** [unoplatform/uno.toolkit.ui#942]
> @MartinZikmund are we gonna have some sort of way of accessing the current Window from the scope of a given UIElement?

_Originally posted by @kazo0 in https://github.com/unoplatform/uno.toolkit.ui/pull/926#discussion_r1409979903_

**Comment by kazo0** [comment]
We need to be able to use the ResponsiveView and the Responsive markup extensions without needing these lines in the app init:

```cs
var helper = Uno.Toolkit.UI.Helpers.ResponsiveHelper.GetForCurrentView();
helper.HookupEvent(MainWindow);
```

@MartinZikmund I believe we were going to have some way of accessing the current window given a UIElement instance?

**Comment by MartinZikmund** [comment]
We should not use `Window` in WinUI, instead it would be appropriate to use `XamlRoot` - which is going to be set when the element is `Loading` and `Loaded`
