### ISSUE TITLE
Uno cupertino getting started with dotnet new

### ISSUE THREAD

**Issue by Darsh0307** [unoplatform/uno.toolkit.ui#980]
## What would you like clarification on:

https://platform.uno/docs/articles/external/uno.toolkit.ui/doc/cupertino-getting-started.html

## Concern?

- [ ] Usage in industry
- [ ] Clarification of capabilities
- [x] Getting started with the Uno Toolkit
- [ ] Developing with the Uno Tookit
- [ ] Contributing to the Uno Toolkit project
- [ ] Publishing your application
- [ ] Support
- [ ] Other (please specify):

## For which Platform:

- [ ] WebAssembly
- [ ] Android
- [ ] iOS
- [ ] macOS (AppKit)
- [ ] Mac Catalyst
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Linux Framebuffer
  - [ ] Tizen
- [ ] Windows

**Comment by agneszitte** [comment]
@Darsh0307 closing this issue as the [documentation](https://platform.uno/docs/articles/external/uno.toolkit.ui/doc/cupertino-getting-started.html?tabs=singleproj#creating-a-new-project-with-the-uno-material-toolkit) already contains the details for dotnet new with the latest updates
Related PR: https://github.com/unoplatform/uno.toolkit.ui/pull/1110
