### ISSUE TITLE
[Chip] re-align with figma design

### ISSUE THREAD

**Issue by Xiaoy312** [unoplatform/uno.toolkit.ui#993]
## Current behavior
![image](https://github.com/unoplatform/uno.toolkit.ui/assets/2359550/3bf468ec-d6ed-4cdd-ab6f-14aeb56a65cc)

## Expected behavior
![image](https://github.com/unoplatform/uno.toolkit.ui/assets/2359550/570402f3-b329-44e1-9288-917a5977dab3)
https://www.figma.com/file/trM3i5qUPmFBcnxWXXmnuF/Uno-Platform-Material-Toolkit?type=design&node-id=4215-68197&mode=design&t=WgRALqyEbPK8ROAr-0

the check-glyph should not be part of the control, 
but the user can decide to add them with the icon property:
![image](https://github.com/unoplatform/uno.toolkit.ui/assets/2359550/7df41769-0011-476c-a324-def64f2e7023)
^ and, they are definitely not associated with the `IsChecked` state

**Comment by Xiaoy312** [comment]
pending approval

**Comment by Xiaoy312** [comment]
ready for pr branch: https://github.com/unoplatform/uno.toolkit.ui/tree/dev/xygu/20240111/chip-check-glyph-removal

**Comment by agneszitte** [comment]
(cc @NVLudwig, @iurycarlos)

**Comment by NVLudwig** [comment]
Would docs need an update as well?

**Comment by Xiaoy312** [comment]
the question first, is do we move forward with this change?

**Comment by NVLudwig** [comment]
@Xiaoy312 From me it's: Yes
@iurycarlos 
@kazo0

**Comment by iurycarlos** [comment]
Didn't manifest before as i thought it was a adm decision. If my vote counts, i'm with Ludwig.

**Comment by kazo0** [comment]
@Xiaoy312 I am good with it, let's do it :)

**Comment by NVLudwig** [comment]
FYI @carldebilly
